### ISSUE TITLE
Add Codebook to Research Page

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#1012]
Pending work on #1007 

![Screen Shot 2020-11-25 at 1 15 35 PM](https://user-images.githubusercontent.com/13560530/100286377-954ccb00-2f27-11eb-9c4b-b09ee1059c52.png)

Real-time Data Downloads
Improving the quality of the Participedia dataset is an ongoing process, and we welcome feedback on any aspect of our data and how we enable its use. Real-time Participedia data is available at the following links:

- [ Download Cases CSV ] and [ Codebook for Cases ]
- [ Download Methods CSV ] (Codebook coming soon)
- [ Download Organizations CSV ] (Codebook coming soon)

**Comment by jesicarson** [comment]
@ascott  - here's a view only public link to the codebook for cases, it can be added to the research page at any time since it's a living document that can be updated via gsheets:

https://docs.google.com/spreadsheets/d/1UnczVqn3U9L1Y8vLTQ2pv6rYI0qMMFEM8f8xXlNz4KA/edit?usp=sharing

**Comment by paninee** [comment]
The codebooks will be a living documents on google drive, so they can be updated if needed. you dont need to do anything to the cases codebook itself, but we want it to be added(as a link) to the research page so that users can access it - as per the mockup above.

**Comment by paninee** [comment]
![image](https://user-images.githubusercontent.com/29439995/104471260-7eae1200-556f-11eb-9a16-4a88133afa0b.png)

**Comment by paninee** [comment]
Deployed and tested on both stage and prod.
