### ISSUE TITLE
Index all text fields for fulltext search

### ISSUE THREAD

**Issue by davidascher** [participedia/api#102]
people will reasonably search for 'france' or 'montreal'. 

(probably don't need to index other bits of the geolocation IMO)

**Comment by dethe** [comment]
Changed title and scope based on conversation with Amber and Jesi.

**Comment by davidascher** [comment]
does that not mean create per-language tables for each field?

**Comment by dethe** [comment]
We are going to have to have a longer meeting about localization soon, I think.

**Comment by dethe** [comment]
At least add:

* [ ] Country
* [ ] City
* [ ] Purpose
* [ ]

**Comment by dethe** [comment]
As of PR #134 we do what this issue originally asked. Need to re-raise this with Amber and Jesi for the other fields, will be complicated to do well and if we're changing metadata a bunch it will me messy to maintain.

**Comment by dethe** [comment]
We increased the number of fields indexed, but indexing *all* fields will wait until we've nailed down exactly what "all fields" are.
