### ISSUE TITLE
Re-verify Google Search Console 

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#1023]

**Comment by jesicarson** [comment]
https://search.google.com/search-console/?resource_id=https://participedia.net/

**Comment by ascott** [comment]
- [ ] update google analytics to latest sdk
- [ ] update TXT record in domain management to verify ownership

**Comment by paninee** [comment]
Need to move from Namespro to Gogole Domain to configure DNS settings.

**Comment by jesicarson** [comment]
@paninee I think we figured out that to do this you can login into the admin@participedia.net google account at domains.google.com and then follow the steps to transfer the domain from namespro. But we'll also have to check about getting a credit card linked up to this account, or using the same account that Mark Warren currently pays for google translate services with. Let me know how I can support.

**Comment by paninee** [comment]
Verified. 
![image](https://user-images.githubusercontent.com/29439995/112551461-44869b00-8d7e-11eb-8ea1-e2154bb43b59.png)

**Comment by jesicarson** [comment]
Thanks @paninee !!
