### ISSUE TITLE
[DEV] Research into language detection for fixing some i18n issues

### ISSUE THREAD

**Issue by ascott** [participedia/api#1024]
- what api to use? ideally google since we are already using them for other i18n stuff
- what is potential cost? will need to run language detection on all rows in localized_texts table, but only need to run on some subset of the data in each row. ie: first 280 characters of body for each entry. is 280 characters enough for accurate language detection?

**Comment by paninee** [comment]
I compared 4 services. I would suggest going with Amazon Comprehend, as it seems to be the least expensive. It's a little bit more expensive than DetectLanguageAPI, but I believe it' would be more stable. Google is probably the best in terms of quality, but it's far more expensive.

~$6 for AWS
~ $5 for Detect LanguageAPI
~$130 for Google

[Amazon Comprehend (Language Detector) - $0.0001_unit.docx](https://github.com/participedia/api/files/5920554/Amazon.Comprehend.Language.Detector.-.0.0001_unit.docx)
[Detect Language API - $5_month.docx](https://github.com/participedia/api/files/5920555/Detect.Language.API.-.5_month.docx)
[Google Translate API - $20_1 million characters.docx](https://github.com/participedia/api/files/5920556/Google.Translate.API.-.20_1.million.characters.docx)
[Language Layer - $19.99_month.docx](https://github.com/participedia/api/files/5920557/Language.Layer.-.19.99_month.docx)
