### ISSUE TITLE
[DEV] Remove Not Applicable & Don't Know values from Cases DB and UI

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#1026]
Re: https://github.com/participedia/api/issues/1007#issuecomment-742029447

Discussion with @Mattygryan @vhurtadol @plscully today to confirm this course of action for CSV cleanup. 

- [x] Review and confirm which ones to remove via [the googledoc](https://docs.google.com/document/d/1eDrUyUyvFRXZyzvsOLJoGmgalt4UfcFCID2q41EgNO4/edit) (Pat)
- [ ] Download case CSV and upload to dataverse as a dated legacy version that includes the don't know's & NA's (D&T)
- [x] Remove na and don’t know’s from database and frontend UI (D&T)
- [x] save a db backup before removing so we can save it for future reference

**Comment by plscully** [comment]
@jesicarson @Mattygryan @vhurtadol  -- I reviewed [the googledoc ](https://docs.google.com/document/d/1eDrUyUyvFRXZyzvsOLJoGmgalt4UfcFCID2q41EgNO4/edit) and added my recommendations. I also noted a few places where we have "don't knows" that weren't captured in the googledoc, but that we need to delete.

**Comment by jesicarson** [comment]
Thanks Pat!

**Comment by paninee** [comment]
Case backup data
[case.zip](https://github.com/participedia/api/files/5882398/case.zip)

**Comment by paninee** [comment]
Completed.
![Communication of Insights   Outcomes](https://user-images.githubusercontent.com/29439995/106042333-c6658b00-6091-11eb-95a1-c10dd3e3966b.png)
![Information   Learning Resources](https://user-images.githubusercontent.com/29439995/106042338-c82f4e80-6091-11eb-9d1d-dfe608828b85.png)
![Decision Methods](https://user-images.githubusercontent.com/29439995/106042340-c82f4e80-6091-11eb-8572-aea9a5f8532a.png)
![Implementers of Change](https://user-images.githubusercontent.com/29439995/106042341-c8c7e500-6091-11eb-8242-29ef315c4497.png)
![Type of Organizer_Manager](https://user-images.githubusercontent.com/29439995/106042344-c9607b80-6091-11eb-862d-07ca87bc2b1d.png)
![If voting](https://user-images.githubusercontent.com/29439995/106042346-c9f91200-6091-11eb-9598-f0993990bdde.png)
![Type of Funder](https://user-images.githubusercontent.com/29439995/106042348-c9f91200-6091-11eb-91c7-32afdd4e492f.png)
![Recruitment Method for Limited Subset of Population](https://user-images.githubusercontent.com/29439995/106042351-ca91a880-6091-11eb-86d2-a4a0a85e3880.png)
![Facilitators](https://user-images.githubusercontent.com/29439995/106042353-cb2a3f00-6091-11eb-8986-4275d5da58e0.png)

**Comment by jesicarson** [comment]
FYI @plscully @vhurtadol this is now complete. does the codebook need any updating? the cases csv from before the change is also linked above.

**Comment by plscully** [comment]
@vhurtadol @jesicarson As Jesi suggests, we will need to update the codebook to reflect the places where we deleted the N/A values. Vero - Can you please take care of this?
Also, per our Jan 8th Zoom call with Matt & Jesi ([notes are here](https://docs.google.com/document/d/1nx5MwCHYuDBYWxD956DabGAUjX-t7LtSrqdKRaktjrs/edit?usp=sharing)) -- we agreed that we should save a CSV of the case data that reflects what the data looked like before deleting the N/A options as a legacy version, label it with toray's date, and upload it to dataverse along with a copy of the companion codebook. As Jesi noted, Pan gave us a link to a zip file (it looks like it's in SQL) to the legacy case file (it looks like it's in SQL so I couldn't open it). There is no big rush on this, but I hope that Vero and/or Jesi can coordinate work to load these materials on Dataverse. Thanks!

**Comment by vhurtadol** [comment]
> @vhurtadol @jesicarson As Jesi suggests, we will need to update the codebook to reflect the places where we deleted the N/A values. Vero - Can you please take care of this?
> Also, per our Jan 8th Zoom call with Matt & Jesi ([notes are here](https://docs.google.com/document/d/1nx5MwCHYuDBYWxD956DabGAUjX-t7LtSrqdKRaktjrs/edit?usp=sharing)) -- we agreed that we should save a CSV of the case data that reflects what the data looked like before deleting the N/A options as a legacy version, label it with toray's date, and upload it to dataverse along with a copy of the companion codebook. As Jesi noted, Pan gave us a link to a zip file (it looks like it's in SQL) to the legacy case file (it looks like it's in SQL so I couldn't open it). There is no big rush on this, but I hope that Vero and/or Jesi can coordinate work to load these materials on Dataverse. Thanks!

Hi @plscully, yes! I've scheduled the update of the codebook for this weekend (to include this and also all the values and labels for the answer options). I'll have it done by Monday. 
I'll use part of my time next week to check the Dataverse work. I'll let you know if I have any problems with this.

**Comment by vhurtadol** [comment]
> > @vhurtadol @jesicarson As Jesi suggests, we will need to update the codebook to reflect the places where we deleted the N/A values. Vero - Can you please take care of this?
> > Also, per our Jan 8th Zoom call with Matt & Jesi ([notes are here](https://docs.google.com/document/d/1nx5MwCHYuDBYWxD956DabGAUjX-t7LtSrqdKRaktjrs/edit?usp=sharing)) -- we agreed that we should save a CSV of the case data that reflects what the data looked like before deleting the N/A options as a legacy version, label it with toray's date, and upload it to dataverse along with a copy of the companion codebook. As Jesi noted, Pan gave us a link to a zip file (it looks like it's in SQL) to the legacy case file (it looks like it's in SQL so I couldn't open it). There is no big rush on this, but I hope that Vero and/or Jesi can coordinate work to load these materials on Dataverse. Thanks!
> 
> Hi @plscully, yes! I've scheduled the update of the codebook for this weekend (to include this and also all the values and labels for the answer options). I'll have it done by Monday.
> I'll use part of my time next week to check the Dataverse work. I'll let you know if I have any problems with this.

@plscully I have updated the codebook with the latest version of the CSV file. I've kept the old version for my records, and the updated version is on google drive ([here](https://docs.google.com/spreadsheets/d/1UnczVqn3U9L1Y8vLTQ2pv6rYI0qMMFEM8f8xXlNz4KA/edit?usp=sharing)).

**Comment by Mattygryan** [comment]
Thank @vhurtadol!
