### ISSUE TITLE
move graphcommons graph to new info@participedia.net account from alanna's account

### ISSUE THREAD

**Issue by ascott** [participedia/api#1047]
https://graphcommons.com/graphs/d743b2ae-3da8-43a3-821a-6bc05f6d103c

**Comment by ascott** [comment]
created a new account for info@participedia.net here and added this account as an admin on this graph. 

https://graphcommons.com/participedia

it doesn't look like i can remove my account from the graph, but now it can be edited/managed by the participedia account and the link/views/stats about it will remain the same.

**Comment by jesicarson** [comment]
Awesome, thanks Alanna!
