### ISSUE TITLE
Implement Auth0 email verification

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#1055]
As a first step to dealing with #1045

**Comment by paninee** [comment]
@jesicarson After looking into what's going on with our user verification, I found that Auth0 sends a verification email to the user before it verifies the account. However, our login logic, does not make use of that `verified` flag, and allows the user to login to the site without their email being verified. I will fix the logic in our code to block the unverified user from logging in.

**Comment by jesicarson** [comment]
@paninee Let's chat about this on Weds. 

I agree that we need to ensure users are verified before they login. I am worried, however, that if some of the spammers are people, not bots, then there's nothing to stop them from verifying their accounts. 

Also, does the user profile page go live before the account is verified? It may not be useful to block unverified users from logging in, since they've already published the spam when they first signed up and created a profile page. Is there a way to ensure an account is verified before they can publish their profile? (but even if we do this we still face the issue of human spammers verifying accounts and publishing them anyway)

I am not sure about the DB columns - if we have the data in Auth0, do we need to store it in our DB? Would any of those columns be useful for the admin only spam blocking page we were considering? #1045

**Comment by paninee** [comment]
@jesicarson the user will see this error when they first signed up and have not verified their email. We can add a link for the user to re-request their verification email later, but I wouldn't add it to the scope of this task. Let's see how the current logic goes first.

Please note that any existing user who has not verified their email address won't be able to login until they verify their email address either.
![image](https://user-images.githubusercontent.com/29439995/113326647-cfabe780-92ce-11eb-8bfe-2f5885052304.png)

**Comment by paninee** [comment]
We need to add a way to allow the user to re-send the verification email as part of this task. I'm working on it.

**Comment by paninee** [comment]
![image](https://user-images.githubusercontent.com/29439995/114647558-27186300-9c92-11eb-8866-e5827b4b3c59.png)
