### ISSUE TITLE
change user's email address

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#1077]
@paninee - i thought i could do this in Auth0 but looks like I can't edit a users email address there. can you help? 

Scott Fletcher (currently scottowenfletcher@gmail.com) wants to update his participedia account to use scott.bowlsby@gmail.com instead. 

Thanks!

**Comment by paninee** [comment]
@jesicarson There are 2 users with the same email in Auth0. One log in using username and password, another one using Google SSO. We cannot change the Google one, but I did change the username/password one.

I also updated the user's email in our database to scott.bowlsby@gmail.com. Please have him try logging in. To make sure it works.


![image](https://user-images.githubusercontent.com/29439995/126693724-8de3cbe4-afaf-4391-a00c-e7bf9dddb3e8.png)

**Comment by jesicarson** [comment]
Thanks Pan, I’ve emailed Scott to let him know.
