### ISSUE TITLE
All related content should be bi-directional

### ISSUE THREAD

**Issue by dethe** [participedia/api#108]
Via Jesi:

When we have related [Case|Method|Organization]s those links should be listed regardless of which way the relationship goes. Likewise, the links should be editable from either side of the relationship, so if Case-23 is related to Method-34, then viewing either of them should show the other as related content, and editing either of them should allow the relationship to be removed. Basically, regardless of where the relationship is originally defined, it should always be treated as bi-directional.

**Comment by davidascher** [comment]
This doesn't feel like an API issue.

**Comment by dethe** [comment]
I put it on API because I'll need to a) return all related content, not just content flagged from a specific item, and b) if the API returns an object, it should be able to handle edits to an object. The front end shouldn't really have to deal with this differently at all, AFAICT.

**Comment by davidascher** [comment]
ah, i see.
