### ISSUE TITLE
Create a vanity url for Participedia internal team site

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#1081]
participedia.net/phase2

Display the internal team google site homepage: https://sites.google.com/participedia.net/phase2

**Comment by paninee** [comment]
@jesicarson should this link be showing up anywhere in the UI?

**Comment by jesicarson** [comment]
The idea is that it’s for for internal use only - to give the team an easy URL to to remember which leads to the google site. 

so I wasn’t planning on linking to it from the site UI because it’s for the team only. It’s a public google site but it doesn’t show up in google searches.
