### ISSUE TITLE
Profile pages returning 404

### ISSUE THREAD

**Issue by dethe** [participedia/api#109]
Haven't dug into why this is happening yet.

**Comment by davidascher** [comment]
is this an API issue?

I'm seeing this on participedia.xyz, which is what I expect:

<img width="1249" alt="screenshot 2017-05-10 14 02 29" src="https://cloud.githubusercontent.com/assets/51278/25921172/5ba1ef66-3589-11e7-8533-38fafe6adaba.png">

**Comment by dethe** [comment]
I think it is, but I spent a lot of time last week debugging and I *really*
want to get editing working before I lose focus again.

**Comment by dethe** [comment]
I have to log in twice, and then get stuck on the redirect page, but I can view the profile page now, so those are different issues.

**Comment by davidascher** [comment]
yes, none of those are api issues, and i'll take care of them.
