### ISSUE TITLE
Verified Entries Feature

### ISSUE THREAD

**Issue by paninee** [participedia/api#1094]
Participedia team members have identified issues with bias and low academic standards in some Participedia.net entries. An editorial board is being formed to review entries. We need a way to identify Participedia.net entries as having been reviewed by this new board, and to prevent open edits that would compromise the integrity of the reviewed entries.

Entries that are reviewed by our editorial board would be identified as such. The reviewed entry would be “view only” and not subject to revision by non-admin users. 

### Dev tasks
- Add 2 new fields in `thing` data table:
  - [x] `reviewed_by` - Store the user ID of an admin who reviewed this entry.
  - [x] `reviewed_at` - Timestamp field of when the entry was reviewed.
- [x] When the user signs in as an admin, show a "Verified" checkbox in the top admin section of the entry create/edit form. See label wording [here](https://github.com/participedia/api/issues/1087#issuecomment-928090406). Make sure they are localized using [Phrase](https://github.com/participedia/api/wiki/Translations-&-Localization).
- [x] When the "Verified" is checked, store the current user as the `reviewed_by` user and the current timestamp in the database when the entry is saved.
- [x] Change the icon of the edit (red pencil) button at the bottom right of the entry view page to the [green checkmark icon](https://github.com/participedia/api/issues/1087#issuecomment-928108263). Grab the SVG from [here](https://github.com/participedia/api/issues/1087#issuecomment-933622547).
- [x] When the user clicks on this green checkmark, display a modal popup `This entry has been reviewed by our Editorial Board and can no longer be edited. If you would like to suggest changes to this entry, please contact us.`
- [x] Create a [migration SQL script](https://github.com/participedia/api/wiki/Migrations) to add a new column. We need to run it on stage and production database.
- [x] when an admin clicks on the green checkmark, they get taken to the edit page instead of the popup
- [x] add a search filter for reviewed entries

**Comment by paninee** [comment]
@jesicarson as an admin, should the verified entry be editable still?

**Comment by jesicarson** [comment]
Yes, they should be editable by admins. An admin can just click the floating button as usual (though in this case it would be the verified button) and be taken to the form.

**Comment by jesicarson** [comment]
when an admin clicks on the green checkmark, they get taken to the edit page instead of the popup

**Comment by jesicarson** [comment]
We may also want to think of a way to add the check mark to the card display of entries in search results (ie a small check mark beside the title text - i can mock this up), and also add a search filter for reviewed entries (these can be new issues)

**Comment by jesicarson** [comment]
![Screen Shot 2021-11-15 at 12 30 03 PM](https://user-images.githubusercontent.com/13560530/141849586-6a802a2d-01c9-4c79-9d68-93ff522b5823.png)

![Screen Shot 2021-11-15 at 12 30 19 PM](https://user-images.githubusercontent.com/13560530/141849608-63f95cd9-c3d7-4336-93ec-66fe26d7f8be.png)

**Comment by jesicarson** [comment]
@paninee [verified badge for search results card svg](https://drive.google.com/open?id=11PvOSx6090Y9DDmnCPLLh24nuIZZN4pU&authuser=jesi.carson%40gmail.com&usp=drive_fs) (15px tall)

**Comment by paninee** [comment]
@jesicarson 15px seem to be too small? 
![image](https://user-images.githubusercontent.com/29439995/142781206-daac490b-431f-42a2-a36a-bf6b754a57ab.png) Maybe 30px?

**Comment by jesicarson** [comment]
I think we should use the icon with just the white check mark on solid green. The “badge within a badge” is not really legible at this size. 

Try that and (if needed) bump up to 20px and see how it feels.
