### ISSUE TITLE
Add captcha on sign up

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#1095]
From David Ascher - Auth0 has support for recaptcha assuming we're still using it. https://auth0.com/docs/configure/attack-protection/bot-detection?_ga=2.226958749.1890185848.1636507724-1735048712.1636507723&_gl=1*164yaws*rollup_ga*MTczNTA0ODcxMi4xNjM2NTA3NzIz*rollup_ga_F1G3E656YZ*MTYzNjUwNzcyMy4xLjEuMTYzNjUwNzc1Mi4zMQ

**Comment by jesicarson** [comment]
@paninee lets talk about when to prioritize this at our next meeting. probably after the "reviewed entries" project, before adding dutch (which is still TBC, waiting to hear from Bonny) or multi language search.

**Comment by paninee** [comment]
![image](https://user-images.githubusercontent.com/29439995/143508262-c2daeb06-7843-43d8-af05-549a5a7e7ec7.png)
