### ISSUE TITLE
Add Nico to collaborators list on about page

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#1111]
Nico Landsman
ZeelandBruist

**Comment by paninee** [comment]
![image](https://user-images.githubusercontent.com/29439995/162525236-f03d2994-91cf-487e-8f51-2f5af6c0a61d.png)

**Comment by jesicarson** [comment]
Hi Pan, 

Thank you for this, however, this list should be in alphabetical order, by last name. Could you please make this change?

Thanks,
Jesi
