### ISSUE TITLE
replace reference to data@ and research@pp.net emails with info@participedia.net

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#1113]
We had to upgrade to a paid google plan so deleting emails we don't use. need to review the site and make sure we don't link to these anywhere.

**Comment by paninee** [comment]
I only found and replace `data@participedia.net` to `info@participedia.net`.

I don't find any reference for `research@pp.net` @jesicarson

**Comment by jesicarson** [comment]
ok. is this on the live site yet? i just checked and there are still 2 data@participedia.net emails on the research page.

![Screen Shot 2022-07-04 at 3 05 49 PM](https://user-images.githubusercontent.com/13560530/177220777-713c8e6a-69b4-4278-8c30-ce2f34b2815f.png)

**Comment by paninee** [comment]
@jesicarson not live yet. It's on stage, ready to be released with the draft feature, but I'm still fixing a few issues with draft and localizations.

**Comment by paninee** [comment]
@jesicarson if it's a rush, I can release this to production separately., I prefer not to because it's harder to track, but doable.

**Comment by jesicarson** [comment]
@paninee no rush
