### ISSUE TITLE
Add Claire Hollenbeck as an admin

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#1125]
Profile: https://participedia.net/user/423009

Email: chollenbeck@clintonschool.uasys.edu

RA for Robert Richards, I'll update the [tracking sheet](https://docs.google.com/spreadsheets/d/1rCyLoVe5RrrbB3N0ZX9n9Jo6QD1zhetJxNwg_E5abcQ/edit#gid=461396618)

**Comment by paninee** [comment]
@jesicarson done
