### ISSUE TITLE
Full screen map

### ISSUE THREAD

**Issue by paninee** [participedia/api#1143]

**Comment by paninee** [comment]
https://github.com/participedia/api/issues/1002

**Comment by jesicarson** [comment]
Add map view icon
Default map view with padding below tabs
Full screen browser icon button on top right of map area (x to close)
<img width="1508" alt="Screenshot 2023-09-07 at 11 35 20 AM" src="https://github.com/participedia/api/assets/13560530/d197018a-c4ee-46cc-bee9-603f56015ee4">
