### ISSUE TITLE
Change 'Sign Up' to 'Apply for an Account'

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#1147]
Issue: we're seeing about 10 daily spam user accounts, with over 10K in the database. I'd guess 90% of these are spam. If you google search for one of the spam keywords, their participedia profile may come up in search results. 

Feature ideas:
- Make adding a bio a requirement, ie: if the bio doesn't express why the user should have an account on Participedia, we won't approve them. (will need to figure out how this works in other languages)
- Require admin approval for all new user account requests

Challenges:
- languages
- barrier to participation
- person required to do the review (staff time, training)
- this system could still be hacked - if real people are doing the spam accounts, they could draft misleading requests for an account and later edit their profile to be spam

**Comment by jesicarson** [comment]
Maybe the language could be "Join our community of editors"

Also doing some research, ie: https://en.wikipedia.org/wiki/Wikipedia:Spam

**Comment by jesicarson** [comment]
https://meta.wikimedia.org/wiki/Nofollow

> On 18 January 2005 the [Google blog](http://www.google.com/googleblog/) entry ["Preventing comment spam"](http://googleblog.blogspot.com/2005/01/preventing-comment-spam.html) declared that Google would henceforth respect a rel="nofollow" attribute on hyperlinks. Their page ranking algorithm now ignores links with this attribute when ranking the destination page. The intended result is that site administrators can modify user-posted links such that the attribute is present, and thus an attempt to googlebomb by posting a link on such a site would yield no increase from that link.

**Comment by jesicarson** [comment]
We're getting about 5 spam user profiles daily, who are all attempting to publish entries, making the review entries task more difficult and complicated. I'm thinking we should close down the site - no new users. Add a message about emailing us to apply to become an editor, something like this. It's becoming un-manageable. Let's discuss on Monday @paninee

**Comment by paninee** [comment]
@jesicarson The "sign Up" label is part of auth0. I dont' know if we can change it, and if that's going to help with spams.

The last time we chatted, we decided not to shut down the site, please let me know if that changes.

**Comment by jesicarson** [comment]
Yes we decided against this approach, in favor of adding <nofollow> to user profiles. This can probably be closed.
