### ISSUE TITLE
Need 'search' to return more fields

### ISSUE THREAD

**Issue by andreadelrio** [participedia/api#116]
Fields needed are:

`bookmarked` and `body` (or a summary of body).

**Comment by davidascher** [comment]
Note that bookmarked will not be meaningful if not logged in.  Fine to either not return bookmarked if not logged in or return a `bookmarked` value of `false.

**Comment by jesicarson** [comment]
Hi - not sure if this is what you're talking about, but if someone tries to bookmark something and they're not logged in, they'll be prompted to login right? same as clicking quick submit if not logged in. Thanks! Ignore me if this is redundant!

**Comment by davidascher** [comment]
It's not redundant (it's a good reminder), but it belongs in the front-end repo issue, it's not relevant for this issue.

**Comment by dethe** [comment]
Fixed in PR #118
