### ISSUE TITLE
make `RESPONSE_LIMIT` settable by the caller

### ISSUE THREAD

**Issue by davidascher** [participedia/api#117]
For data analysis, it'd be convenient to export the full data set in a JSON blob per data type.  I propose:

`/bulk/cases`, `/bulk/methods`, `/bulk/organizations` which each return a single JSON blob with all of the data of each type in one response.

@dethe thoughts?

**Comment by davidascher** [comment]
Actually, I think all we need to do is to be able to disable pagination on `/search`.  

`/search?query=&selectedCategory=Methods&page=2&sortingMethod=alphabetical` seems to work OK, and indeed returns more data than the default search, which confuses me a bit.

**Comment by davidascher** [comment]
Updated the title to say what I mean.

**Comment by dethe** [comment]
We have pagination and bulk export now, closing.
