### ISSUE TITLE
case submission of images is not working the way i expect it

### ISSUE THREAD

**Issue by davidascher** [participedia/api#151]
the quick case submit (with a fix that's incoming) is sending a case with a `lead_image` which is `{url: "blahblah.jpg"}`, but the API ends up storing `("[object Object]","",)` in the `lead_image` sql column.  

<img width="663" alt="screenshot 2017-06-17 00 57 47" src="https://user-images.githubusercontent.com/51278/27251253-402644bc-52f8-11e7-89ab-5e5ece455dfc.png">

**Comment by davidascher** [comment]
seems like i need to send just urls, not `{ url: ___ }` which seems symmetry-breaking.

**Comment by dethe** [comment]
It should work with either a list of URLs or a list of {url: ""} objects. I'll double-check.
