### ISSUE TITLE
Finish populating Case JSON from subtables

### ISSUE THREAD

**Issue by dethe** [participedia/api#18]
The first cut at generating JSON from Postgres was focussed on getting things working. Now we need to flesh it out. We currently pull in data from the main `cases` table, `case___authors`, `case__localized_texts`, and `geolocation`, but we want to also pull in:

* [x] `case__attachments`
* [x] `case__methods`
* [x] `case__tags`
* [x] `case_videos`

**Comment by davidascher** [comment]
"from the postgres"?

**Comment by dethe** [comment]
Note: `case__methods` table appears to be completely unpopulated, will need to fix that in data import.

**Comment by dethe** [comment]
Fixed in PR #19
