### ISSUE TITLE
Design and Implement CSV export

### ISSUE THREAD

**Issue by dethe** [participedia/api#233]
For CSV export of cases, methods, organizations, et cetera.

This is the requirements for the server-side of this feature. For the client UI, if any, see https://github.com/participedia/frontend/issues/674

Before any implementation work is done, we need to agree on a mapping. Currently the data for a case (etc.) is divided among several tables in the database and is returned as JSON, allowing nested structures. CSV does not support nesting, so we will have to document how the mapping works. For example, `related_cases` is a list of `{title:, id: }` objects, while `images` is a list of strings, and `location` is an object with its own properties. Some options (there may be others), each with their own tradeoffs.

1. Flatten objects (like `location`} from `location: {city:, country:, latitude:, longitude:}` to fields: `location_city, location_country, location_latitude, location_longitude`, basically un-nesting them.
2. Have api to dump locations in a seperate CSV file and only include ids of locations from that file in the dumped cases CSV (this is the relational way, but not very friendly for Excel import).
3. include escaped structures in a single column of the CSV. These structures can be CSV-escaped JSON, CSV, XML, or HTML, essentially embedding nested objects within the CSV output.
Again, not very friendly for Excel import.
4. Flattening objects will not work for lists, which may include 0 or more nested objects or strings. So we may be forced to use options 2 or 3 above for those.

Agreeing to and documenting this mapping is the most important thing, because it will not only be needed for the implementation, but for anyone using the exported data, and crucially for maintaining the export functionality when the data model changes.

Implementation requirements:

1. Have an agreed-upon mapping
2. Implement in NodeJS based existing Participedia codebase
3. Work submitted as a PR against this repo
4. Includes tests

**Comment by TheAndyCameron** [comment]
Addressing requirements 1 for the mapping, as you said, the main issue is fields that can contain multiple values.  

# In Industry

We have looked at some examples of other implementations of this problem to see if there was an industry standard. The most common solution seemed to be using an additional separator to distinguish values within a field. [Drupal uses pipes as the main separator and tildes as a secondary separator](https://i.stack.imgur.com/EgtMR.jpg). Emarsys recommend [using pipes as the secondary separator](https://help.emarsys.com/hc/en-us/articles/115004559625-CSV-Guidelines#field-with-multiple-values).
An alternative solution that JIRA uses is [additional fields for multiple values](https://confluence.atlassian.com/adminjiraserver073/importing-data-from-csv-861253680.html#ImportingdatafromCSV-AggregatingmultiplevaluesintosingleJIRAfields). We didn’t like this as it seemed clunkier, and either requires you to limit to `x` total values, or to know the maximum number of values that each entry takes and expanding dynamically, neither of which seem like optimal solutions.

# Proposed Solution

As such, we believe that using Dethe’s option 3 with nested CSV would be a simple solution to go with.

For example:

### Simple Lists:
We’re considering using pipes (`|`) for fields with multiple values. A list field such as tags would use a single field with the separator to contain multiple values. Say if we have a list of tags: `tags: [‘tag2’, ‘tag2’, ‘tag3’],` we could map them into a single field:
`..., tags, ...`
`..., tag1 | tag2 | tag3, ...`
Essentially encoding the list into the single field.

### Object Lists:
Objects with multiple fields would be expanded into a CSV column for each field. A list of authors may have the structure `[{‘id’:0001,’name’:’Jim’},{‘id’:0002,’name’:’Sarah’},{‘id’:0003,’name’:’Ryan’}]`. We would map this to:
`..., id, name, ...`
`..., 0001 | 0002 | 0003, Jim | Sarah | Ryan, ...`
This would be listing 3 authors: Jim with ID 0001, Sarah with ID 0002, and so on.
This allows us to maintain the position of the columns while still allowing `n` sized lists in the JSON.

Is this satisfactory? If so, we’ll begin with design, tests, and implementation.

**Comment by dethe** [comment]
This sounds good, I think we can work with it. We'll need to specify how commas and pipes if they appear within the values.

Definitely agree we don't want to vary the number of columns or have to know/restrict in advance how many things will be in a list. The Object Lists proposal looks a little strange, but should work. One nice features is that lists of strings and lists of objects will be very similar in structure.

I suggest a naming convention for fields that can contain lists, so if there is data which at a glance appears to be empty or only hold a single value, that someone working with it still is clued in to expect lists. This can be as simple as those header columns having names that end with "_list".
