### ISSUE TITLE
Track .net changes for manual transfer to .xyz

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#246]
Import from .net overwriting .xyz issue:
Instead, dethe will set up rss or email notification for new changes to .net that can be managed manually by staff
Pull export from .net daily and compare to previous day to see what has changed
Dethe just needs the email address of the people who will be doing the manual work (lucy, scott, ethan)

**Comment by jesicarson** [comment]
lucy.parry@canberra.edu.au
scottowenfletcher@gmail.com 
ethan.way@mail.utoronto.ca 

I assume we need to set up the system first, and then have a call to explain how its going to work with these guys and Pat.

**Comment by dethe** [comment]
As part of the admin system, allow articles from .net to be imported into .xyz by ID.
