### ISSUE TITLE
Pre-process images

### ISSUE THREAD

**Issue by dethe** [participedia/api#285]
Right now we are delivering images in their original size and scaling them in the browser, which is a waste of bandwidth. We should scale them appropriately and send in a fixed size (possibly still scaling in the browser as needed) and also compress and optimize the images to minimize customer bandwidth use.

**Comment by ascott** [comment]
for all images already saved to s3 and for all new images uploaded
- [ ] add cache-control/ttl headers
- [ ] scale and save images to set sizes (tbd, but likely large, med, thumbnail)
- [ ] save and optimize as jpgs
