### ISSUE TITLE
Implement Case Edit page and all edit widgets

### ISSUE THREAD

**Issue by dethe** [participedia/api#336]
### HTML Templates needed

To be implemented in HTML only
------
* [x] _Text property (edit-text)_
* [x] _TextArea property (edit-textarea)_
* [x] _Select property (edit-select)_
* [x] _Date picker (edit-date)_
* [x] _Number picker (edit-number)_
* [x] _Boolean/single checkbox (edit-boolean)_
* [x] _Authors edit (admin only)_
* [x] _Floating Publish Button_
* [x] _Submit button_
* [x] Full vs. quick

Fields that need JS
------
* [x] _Rich text edit (edit-richtext)_ 
---- use [proseMirror](https://prosemirror.net/)
* [x] _Location picker (edit-location)_ 
---- use [Google Places API](https://developers.google.com/maps/documentation/javascript/places-autocomplete) 

* [x] _MultiSelect with ranking (edit-multi-select)_
---- use html5 drag and drop with mobile shim

* [x] _Media/Files picker (edit-media)_
---- needs JS for drag/drop to upload and showing file/image selected
* [x] _Media/Photos picker (edit-media)_

* [x] _Media/Audio, Video, Links Links  (edit-media-links)_
---- html in place, needs JS to add/remove input sets for each link (link, title, attribute)

First cut is to implement these as plain HTML + CSS, after that we'll look at converting them into more full-featured widgets when JavaScript is available.

**Comment by jesicarson** [comment]
@ascott Included here is the rank order question type, which is the same as the media/files re-ordering system, visually. Make sense? Let me know what you need in terms of vector files. This mobile mockup is currently in the PAGES Mockup for Awards-Cleaned up.ai file, under 2018 mockups, but I will create a new .ai file for mobile I think. I have to go offline for the rest of today, but will be back tomorrow to finish cleaning up the filing system. Thanks for your patience and hopefully this is good for now. 

![100 form mobile spec](https://user-images.githubusercontent.com/13560530/49469866-78101680-f7bd-11e8-8d1e-db0ed250a2bb.jpg)

**Comment by jesicarson** [comment]
@ascott 
- should the form field design match what is currently on .xyz? in particular the ranked list field, and the file upload field?
The mockups above should be the design reference, unless it saves a lot of time to reuse elements from xyz, let me know. (but spacing and type at least should be adjusted to match mockups)

- what is the logic for the quick submit vs. full form? on initial load should we show only quick submit fields? and then show all fields once the full button is pressed?
Yes, initial load shows only quick submit, then load all fields once button is pressed. Use the same headers/ dividers as full version in quick submit.

- what should the form validation/errors look like?
this is on my to do list! dark overlay over page, white box with warning text, options to continue to exit (and lose un-published changes) or return to publish.

- which fields are required? i didn’t notice that noted in the content spreadsheet
only title is required

**Comment by ascott** [comment]
@jesicarson how should the multi select fields look? should they match what we have on xyz?

<img width="468" alt="screenshot 2018-12-14 14 38 11" src="https://user-images.githubusercontent.com/130878/50033604-09e20580-ffae-11e8-987b-c5853c110e96.png">

**Comment by jesicarson** [comment]
Ah good catch. I don’t have a mock-up, but we’d like to see the list of selected components below the field box, not in it. Visually, this should match the multi select and rank question (general issues) shown above in the mobile mock-up, but without the ranking part, so just a grey outline with the x on the right. I also want to update the mock above so that the multi select and rank values are listed left aligned rather than indented 15px. 
I can try to get u mocks for these ASAP. Is this enough to go on for now?

**Comment by ascott** [comment]
ok, yeah that's enough to go on. thanks!

**Comment by jesicarson** [comment]
@ascott based on what we talked about today, and the samples you sent me, here's an updated mockup for mobile case form:
![form-mobile-dec 17 2018](https://user-images.githubusercontent.com/13560530/50105660-37af9000-01e2-11e9-9667-f739890c58b9.jpg)
