### ISSUE TITLE
Design review of Organization form/ reader

### ISSUE THREAD

**Issue by ascott** [participedia/api#391]

**Comment by jesicarson** [comment]
@ascott anything from me needed?

**Comment by ascott** [comment]
@jesicarson yes, once we get staging fixed it would be great to get your eyes on methods and orgs. the design/styling should all be the same as cases but want to make sure we haven't missed anything.

**Comment by jesicarson** [comment]
Sounds good. Ping me when staging is back online. Thanks!

**Comment by ascott** [comment]
@jesicarson this is ready for your review on staging
