### ISSUE TITLE
Faceted Search on Homepage

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#480]
NOTES:
Pat will provide the key data fields/ values for faceted search.

For now, faceted search doesn't have to be linked to download (because download will be a later update, post-PR-launch) but eventually we want users to be able to download sets of search results from faceted searches.

[ @plscully is this accurate? ] There may be two ways of thinking about downloads generated by faceted searches: 
1. Downloading a spreadsheet **containing all data** for a set of results (generated by faceted search, reducing results).
2. Downloading a spreadsheet **containing only selected facets** for a set of results (also generated by faceted search, but less cluttered with other data). 
I figured we'd be doing [ 1 ] but after talking to pat it seems that he was thinking [ 2 ].

Also related to [ 2 ] is this system designed by the Southampton students for selected facets within the download feature.. So you can download a set of search results (faceted or not) and from there further narrow down the data you want in your spreadsheet: https://github.com/participedia/frontend/issues/674 

I will post the early faceted search mockups for the homepage here also.

**Comment by jesicarson** [comment]
![Home 3 Column Results with Sidebar - current](https://user-images.githubusercontent.com/13560530/55838798-8018f380-5ada-11e9-8a00-3d0915421a98.jpg)

![Pp xyz April 24 Screenshot](https://user-images.githubusercontent.com/13560530/55838799-80b18a00-5ada-11e9-9682-b108df65fddd.jpg)

**Comment by jesicarson** [comment]
Will need to work on design, but you get the idea.

**Comment by plscully** [comment]
@jesicarson Now that I look at what you reported above, you are correct that #1 is the only option we need to consider for downloads generated by faceted search. That is we DO NOT need to include a feature that produces a spreadsheet containing only selected facets for a set of results. Users can simply work with a download that includes all the facets, and then delete fields/columns they don't need.

**Comment by jesicarson** [comment]
Thanks Pat. We'll go with that. Still needs to be designed though, so reopening this :)

**Comment by jesicarson** [comment]
Here's the draft list for faceted search fields: https://docs.google.com/document/d/1hhm7o9olglAj9m5YqdcT2JwTFezCMoEKufvR74yhQEw/edit#

**Comment by jesicarson** [comment]
@ascott thinking about options, would love your opinion re: usability.
1. include facets in the "sort by" drop down
2. include "more options" below the options in the sort by drop down, which if clicked opens the left column of results as shown in the mocks above, revealing the facets
3. include facets in the hamburger menu, below the buttons
4. always show facets on homepage

**Comment by jesicarson** [comment]
Here's a mockup for consideration. Realized the draft list above is just for cases, so assume that faceted search would be revealed in the left column of results when the Cases tab is clicked. Sort by would function as normal, in addition to facets. In this mockup, drop downs work the same way they do on the about page, revealing facets. And facets can be selected by clicking them, which would turn selected facets red and filter the results accordingly. If clicked again, that would turn the text black and remove that facet from the search, so results would re-generate. 

![Faceted Search CASES Draft 1](https://user-images.githubusercontent.com/13560530/55922976-62ba5700-5bb8-11e9-92f3-341d80bb3beb.jpg)

**Comment by plscully** [comment]
I like this! Feels like the left column needs a header. Perhaps "Refine your search" or maybe just the straightforward "Faceted Search". That is a term of art, right? https://en.wikipedia.org/wiki/Faceted_search

**Comment by ascott** [comment]
i agree a heading would be useful on the left hand column. I wonder if `Filter Results` would be more clear/understandable to users than `Faceted Search`.

could we add check boxes beside each facet to make it clear they are clickable and selected or unselected? this will also help improve accessibility.

perhaps we could have a link beside the sort by dropdown called `Filter Results` that would open the filter list on the left.

**Comment by plscully** [comment]
I like the "filter results" option for a header.

Check boxes are also good. If possible, I would love to replicate the functions of  participedia.net 's faceted search. It's not pretty, but it does the trick in terms of allowing you to see the options and to see which values you've selected.

**Comment by jesicarson** [comment]
AI Design File [Here](https://drive.google.com/open?id=1VFdO13VYgbDLep5daTxfP-mJ2M2eOcdc). Latest mockups below. Using Google Material Design [chips](https://material.io/design/components/chips.html#usage) as the horizontal, stackable UI elements. Containing drop downs with check boxes. 

Cases Default
![1 FS V4 - cases default](https://user-images.githubusercontent.com/13560530/57330722-bb9fe100-70cb-11e9-8770-5d310bffbef2.jpg)

Chip Open
![2 FS V4 - chip open](https://user-images.githubusercontent.com/13560530/57330723-bb9fe100-70cb-11e9-815f-2910a874ae6a.jpg)

Chip with selections + another chip open
![3 FS V4 - chip with selections and another chip open](https://user-images.githubusercontent.com/13560530/57330724-bb9fe100-70cb-11e9-96df-74bca4043443.jpg)

Chips on 2 lines
![4 FS V4 - chips on 2 lines](https://user-images.githubusercontent.com/13560530/57330725-bb9fe100-70cb-11e9-891d-cfc263d18c36.jpg)
