### ISSUE TITLE
article edit/update description field bug

### ISSUE THREAD

**Issue by ascott** [participedia/api#494]
when clearing the description field and saving i would expect it to save an empty/null value for the description, but it continues to save the old value. replacing the string with new text works as expected.

![participedia-description-bug](https://user-images.githubusercontent.com/130878/56238958-9ed03a80-6044-11e9-8015-95ac23468740.gif)

**Comment by paninee** [comment]
https://github.com/participedia/api/tree/pan-494

Created new PR https://github.com/participedia/api/pull/758
