### ISSUE TITLE
Some dates getting reset to null when edited by an admin

### ISSUE THREAD

**Issue by dethe** [participedia/api#507]
I don't know yet if this is due to things like `post_date` not being sent or the valiidation not working on existing dates.

**Comment by dethe** [comment]
Update, this is only happening when logged in as admin, so I think it is because the front-end may not be sending `post_date` or other read-only fields. And normally that's fine, but admins can update `post_date` and authored by (this is so Scott can move articles from the old site without making himself the author or changing the original dates.

**Comment by ascott** [comment]
@dethe would you prefer to always receive `post_date` from the client or only when an admin is updating this field?

**Comment by dethe** [comment]
You can always send it, the backend will ignore it unless the user is admin.

**Comment by ascott** [comment]
looked into this, and the frontend was not setting the value of post_date correctly when the user was an admin, so that's why it was getting sent up as null. will open a PR with a fix.

**Comment by ascott** [comment]
@dethe we should also probably validate `post_date` and not allow it to be set as null.

**Comment by dethe** [comment]
Agreed
