### ISSUE TITLE
Map Issues

### ISSUE THREAD

**Issue by ascott** [participedia/api#530]
changes to map functionality
- on all tab: show all cases and orgs with black pins. show featured articles with red pins
- on cases and orgs tabs: show all cases or orgs depending on tab with black pins, show featured with red pins
- methods tab shows no pins
- if with search term, map only shows results with black pins, and shows featured articles in red pins
- use /search?selectedCategory=All&resultType=map endpoint to get map results

**Comment by jesicarson** [comment]
@ascott that doesn't quite sound right. 
Featured items are always red. Cases and orgs are always black. 
Search terms removes any pin from the map that doesn't match the search.

**Comment by jesicarson** [comment]
Clicking the cases tab would remove any orgs pins from the map, and vice versa. Methods tab would show no pins.

**Comment by jesicarson** [comment]
or maybe your second bullet point meant that featured items remain red and this is all saying the same thing :P  Sorry if i misread that.

**Comment by ascott** [comment]
i think we are saying the same thing. i updated the issue to hopefully be more clear.

**Comment by jesicarson** [comment]
yepppp perfect thanks!
