### ISSUE TITLE
remove gravatar for profile photos

### ISSUE THREAD

**Issue by ascott** [participedia/api#537]
- use user initials for profile photo badge
- remove change photo link on edit profile page

**Comment by jesicarson** [comment]
We can probably leave it as is for now @ascott 
The issues I bumped into were because i returned to production rather than staging. so i actually did get it to work. its annoying yes, but it does function. if its more work to strip out we may want to leave it but ill let you decide.

**Comment by ascott** [comment]
ok, let's leave it in for now then and revisit later.
