### ISSUE TITLE
missing images on profile page: update the user profile json to include image urls or the placeholder url 

### ISSUE THREAD

**Issue by ascott** [participedia/api#538]
placeholder image urls are not being passed with article data on user profile page.

we need to update the user profile json to include image urls or the placeholder url for user profile contribution and bookmark article images.

<img width="703" alt="Screenshot 2019-05-06 21 58 09" src="https://user-images.githubusercontent.com/130878/57272826-1d1f6b80-704a-11e9-836b-15968aed6aee.png">

**Comment by dethe** [comment]
Partially fixed: in PR #608 I added the AWS prefix to images that didn't have it, which fixed existing images. Still need to add placeholders for articles missing images entirely.

**Comment by ascott** [comment]
tracking this issue here: https://github.com/participedia/api/issues/612
