### ISSUE TITLE
/method/edit backend issues - purpose_method and level_complexity not getting saved

### ISSUE THREAD

**Issue by ascott** [participedia/api#553]
- [ ] `purpose_method` is not getting saved
- [x] `number_of_participants` should be an integer but looks like the db is expecting it to be array?
- [ ] `level_complexity` is not being saved to the db

**Comment by dethe** [comment]
`number_of_participants` is an array of keys representing up to three of the following values (in ranked order):
```
Individuals
Small groups (e.g. less than 20 people)
Medium size groups (e.g. around 50-100 people)
Large groups (eg. more than 100 people)
There is no limit to the number of people who can participate
```

**Comment by ascott** [comment]
ah, i see. i was mixing this up with the case filed called `number_of_participants`. i'll fix the frontend for this.

**Comment by dethe** [comment]
I thought it would be a number too. No idea why 😉
