### ISSUE TITLE
fix missing keys on method reader page

### ISSUE THREAD

**Issue by ascott** [participedia/api#563]
![image](https://user-images.githubusercontent.com/130878/57641384-bdedb980-7569-11e9-853e-eef9bcd33e3d.png)

https://github.com/participedia/usersnaps/issues/384

**Comment by ascott** [comment]
@dethe this looks related to the changes in the data model for methods. have you run the migrations related to this mapping yet so existing values get mapped to the new values? 
for example it looks like `4-Polarized` should now be `polarized`. we have localized text mapped to the new values and not the old values, which is why we are seeing this on the front end.

https://github.com/participedia/api/blob/master/doc/new_methods_mapping.md#issue_polarization.

**Comment by dethe** [comment]
@ascott Was this just for `level_polarized`? I don't see any bad data in the live database on staging for `scope_of_influence` but there are two stray values that didn't get mapped in the migration for `level_polarized` due to typos. I've fixed the typos, so they will be OK in the real migration, and I fixed it by hand on staging.

**Comment by dethe** [comment]
I take it back, it doesn't look like these were migrated on staging. The same migrations on my local are OK, so not sure what is going on, but on staging `level_polarization` looks like it is still `issue_polarization` and still has old data. I'll look into this tomorrow after work.

**Comment by dethe** [comment]
OMG, that's what I get for for working too tired. I was looking at the prod database, not the staging one, so it looked like none of the migrations had gone through. Panicked myself good. Fortunately, I wasn't making changes to it!
