### ISSUE TITLE
search: resultType=map endpoint with a query param should only return the results for that query

### ISSUE THREAD

**Issue by ascott** [participedia/api#564]
search: resultType=map endpoint with a query param should only return the results for that query

- currently it returns the same results as it does without the query param.

/?resultType=map&query=canada&returns=json

**Comment by dethe** [comment]
This is working as designed (we can certainly change the design). If no query is specified (or if the user searches for 'featured') there is a default search for featured items. All items are returned, but featured items are listed first, then all the rest. Featured items have their featured flag set, as usual, but also have `searchmatched: true`, as do query results when there is a full text query.

The returned JSON also has properties for `total` (how many results altogether), `searchhits` (how many of the results matched the search criteria, on localhost this gives me 4 for the default search and 211 for the Canada query), and `pages` for how many pages of results (always 1 for map results).

The default/featured search is actually an example of faceted search, so if we want changes to how it works I can include that in the overall faceted search work pretty easily.
