### ISSUE TITLE
edit form: error with static data for cases, methods and orgs 

### ISSUE THREAD

**Issue by ascott** [participedia/api#574]
eg: /case/5239/edit?full=1

cases, methods and orgs data as part of the static key are being sent to the client with null values for the titles.

<img width="701" alt="Screenshot 2019-05-14 16 09 47" src="https://user-images.githubusercontent.com/130878/57738296-b7436d00-7663-11e9-804e-9a66c80a991d.png">
<img width="575" alt="Screenshot 2019-05-14 16 09 40" src="https://user-images.githubusercontent.com/130878/57738297-b7dc0380-7663-11e9-8da2-5cca7b91ccec.png">
<img width="702" alt="Screenshot 2019-05-14 16 09 32" src="https://user-images.githubusercontent.com/130878/57738298-b7dc0380-7663-11e9-931c-2a27be113b57.png">

<img width="698" alt="Screenshot 2019-05-14 16 21 37" src="https://user-images.githubusercontent.com/130878/57738455-62ecbd00-7664-11e9-8d4f-4408d7723511.png">

**Comment by dethe** [comment]
Interesting. The titles are returned wrapped in escaped quotes, then turned to null when `to_json()`. I've seen a few issues around strings being escaped multiple times, will need to address this in the migrations + validation layers.

**Comment by ascott** [comment]
let me know when you think you might be able to get to this. i need this to be able to finish implementing the autocomplete fields. https://github.com/participedia/api/issues/584 thanks!

**Comment by dethe** [comment]
This was trickier than I thought, but should be working now. Going to have to come up with a more robust caching system as we support more languages though.
