### ISSUE TITLE
Create proxy

### ISSUE THREAD

**Issue by andreadelrio** [participedia/api#6]
We are having trouble accessing Auth0 API from within localhost:3000
@dethe suggested creating a proxy might be a soluction.

To replicate the issue you can go to the `frontend`'s branch called `profiles` and visit http://localhost:3000/en-US/otherprofile open the console and click on text "click to get info of a user". 
You should see:

![image](https://cloud.githubusercontent.com/assets/4016496/21959436/d367638c-da7b-11e6-9324-ecc7baa08d94.png)

**Comment by dethe** [comment]
Thinking about this later I have some concerns about the goal here? What information are we trying to display in a user's profile when other users view it?

**Comment by andreadelrio** [comment]
@dethe I would say name, last name and description (this last one they'll be able to add from within their Participedia profile).

**Comment by davidascher** [comment]
@dethe I assume your question is about the desirability of the feature, not the implementation, yes?  Feel free to ask jesi/amber about it for details.  The general idea is that there is a hypothesis that people will want to create a 'reading list' of sorts -- cases and methods in particular that they think people who are interested in their research interests for example might be interested in reading about.  The profile, therefore, is essentially a public-facing artifact.

I think it's a fine thing to test with user testing.

@andreadelrio can you send a link to the code that is doing the auth API call?  I'm not sure what call is failing.

**Comment by andreadelrio** [comment]
@davidascher 
https://github.com/participedia/frontend/blob/profiles/src/actions.js#L96

from here:
https://github.com/auth0/node-auth0

**Comment by davidascher** [comment]
Looks like that API is CORS-restricted.  The doc says: "This document
describes v2 of the Auth0 API, which is meant to be used by back-end servers
 "

So yes, that API will need to be called by the API endpoint.  Which is
probably fine, it will force us to understand exactly what profile changes
we want the app to be able to make, and define an API which we can then
target to Auth0 (but will be able to move to some other DB if necessary).

Do you want to take a stab at defining the REST API you, from the front-end
point of view, want, and I can build the proxy?

**Comment by davidascher** [comment]
So in this case, I think what we need is to define the `/users` part of the API, to give the front-end what it needs.  I suspect something like:

* `/users` --> list, with pagination, the IDs of all active users
* `/user/<id>` --> return the public data about user `id` in JSON format

etc.

**Comment by andreadelrio** [comment]
@davidascher yes, for profiles in particular I would need `/user/<id>` as a priority. Regarding IDs, would we be publicly showing the ones from Auth0? In the form of `participedia.com/user?id=google-oauth2|1122223198527859340` ? Was wondering if that is safe or if we should internally map new IDs that we generate to the ones of Auth0.

**Comment by davidascher** [comment]
Probably makes sense to have our own IDs that map to auth0 IDs.

**Comment by davidascher** [comment]
So, thinking about this a bit, I suspect we need a few things to happen.

any call to `/user/*` should first check to see if we have a record in our user DB for the currently logged in user.  If no, then a user record needs to be created, generating a user ID along the way (I suggest we generate numeric IDs for now which leaves the option of letting users generate usernames in the future.

I suggest that that DB be another dynamodb table.

But that makes me think that we should think about the old users table (`pp_users`) and what data we want to keep from that table, and/or how we think about users who used to have accounts and how they show up in the new system as well.

I suspect the only thing we care about from the last user DB is the uid which is used in references in cases etc. as the author or last editor of a record.

**Comment by davidascher** [comment]
I believe this is no longer necessary.
