### ISSUE TITLE
Full text search with no results breaks

### ISSUE THREAD

**Issue by dethe** [participedia/api#606]
Need to handle this case gracefully.

**Comment by dethe** [comment]
Nevermind, didn't break, just took longer than I was expecting.

**Comment by jesicarson** [comment]
@ascott We should use the “... loading results” thing like xyz, and like how you handled the slow publishing scenario. I think there’s an issue for this for loading search results.

**Comment by ascott** [comment]
@dethe how long did it take? is there anyway to speed it up.

@jesicarson loading feedback here would be useful but we are using a different pattern for fetching the results here than we are when we are publishing an article. it's definitely possible to do but there are a number of things we would have to do to make it work with the current setup. i can explain in more detail at our mtg wednesday if you'd like.

**Comment by jesicarson** [comment]
Ok fair enough. We can come back to the loading feedback when we get to the design backlog items.
