### ISSUE TITLE
Deleting entries (for good)

### ISSUE THREAD

**Issue by scottofletcher** [participedia/api#616]
@ascott @dethe @jesicarson  
I asked about this a while ago, but we've had a situation come up with one of our partners that necessitates that we create a way to either 
1. delete entries for good or 
2. re-route non-admin users that click on a link or enter the exact URL of a 'hidden' entry to a page that says 'this entry has been deleted'

'Hidden' cases are still accessible if they were entered in any of the database-search fields (eg. components, specific methods, organizing entity) or if they were hyperlinked to in the narrative body. They should only be accessible by admins.

**Comment by jesicarson** [comment]
Good point and this should get implemented. Probably not super high priority though, right Scott? 

At least we can hide all the tests and messy stuff, and chances are if it was entered in error it may not be linked to too many other entries (as a method/component etc) right?

Hiding is the MVP, properly hiding is nice to have. But correct me if it’s more urgent. Thanks!

**Comment by scottofletcher** [comment]
@jesicarson I'm not sure how urgent it is, I'm waiting to hear back from Julien and Mark regarding the 'situation'. I'll forward you the email. I think the person whose work was plagiarized is going to be none-too-pleased that she can still access it by clicking a link

**Comment by dethe** [comment]
I can return an error if a non-admin tries to access a hidden article easily enough. Will need some front-end work to handle the error and show a nice message. The message itself should be part of our UI localizable text.

**Comment by scottofletcher** [comment]
@dethe great! thank you!

**Comment by ascott** [comment]
do we need a page that says 'this entry has been deleted' or can we just return a general 404 page?
@jesicarson do you have a design for a 404 page?

**Comment by jesicarson** [comment]
@ascott I don't have a mockup, but would be nicer to have a page, or what about our standard modal/popup/warning format? Could that work?  And yes use the text: "This entry has been removed"

**Comment by jesicarson** [comment]
@scottofletcher combatting plagiarism does feel urgent.

**Comment by jesicarson** [comment]
@ascott are you ok without a mock if we just use the standard modal?

**Comment by scottofletcher** [comment]
Sounds good all!

**Comment by ascott** [comment]
@jesicarson and i just discussed via slack, and we decided on a general 404 page to handle requests to hidden pages as well as invalid url's. @dethe i can implement the 404 response from the server if the article is hidden as well.

**Comment by scottofletcher** [comment]
ok, but I think this is going to leave users wondering why they can't access an entry in which case they might email us and we'll have to explain. which reminds me: we never finished creating a work-around to the internal messaging system. unlike on .net, if users have a question about an entry, they can't contact the original submitter (unless they provide contact info on their profile page). we started on this here: http://bit.ly/2EtcbR4
