### ISSUE TITLE
user biographies and names did not transfer from .net to .xyz

### ISSUE THREAD

**Issue by ascott** [participedia/api#625]
https://participedia.xyz/user/278156
on .xyz 
![image](https://user-images.githubusercontent.com/130878/58440781-831f7180-8091-11e9-9005-b4d802c267d3.png)

on .net
![image](https://user-images.githubusercontent.com/130878/58440787-8b77ac80-8091-11e9-9714-c5c0361f83bd.png)

reported here: https://github.com/participedia/usersnaps/issues/700

**Comment by dethe** [comment]
Yes, that is correct. User bios were not included in the .net export of users and have never been part of the new Participedia site. They have been absent from the site for about 2 years now and would require writing a web scraper to extract them from the users who have them on .net.

@jesicarson is this worth holding up moving .net to point to the new site?

**Comment by jesicarson** [comment]
@dethe no this is not worth holding up the transfer. if it becomes a problem, people complaining etc, we can deal with the scraper idea later.
