### ISSUE TITLE
improve quick submit to full version flow

### ISSUE THREAD

**Issue by ascott** [participedia/api#627]
current flow:
- a user edits fields in quick submit view, clicks full version and is prompted with the `leave site?` alert.
- they then need to press cancel, then publish, which saves and takes them to the reader view. from there they need to click the edit button and then the full version button to edit the full version form.

new user flow:
- a user has edited fields in the quick submit view, and clicks full version button
- we show the publish modal, then load the full version edit form

**Comment by ascott** [comment]
@jesicarson do you have any feedback on this new flow, or does this sound like what you were thinking as well?

**Comment by jesicarson** [comment]
Previously the production site used this flow, which I think works:
- User clicks publish/edit and gets the quick sub form
- User makes edits to one or more quick sub form fields
- User clicks "do full version"
- Full version loads with edits already made to the quick sub form persisting (no loading of publish modal)
- Clicking publish publishes all edits made to quick and full versions
