### ISSUE TITLE
implement search filters for methods and orgs tabs

### ISSUE THREAD

**Issue by ascott** [participedia/api#675]
fields to be filtered TBD.

**Comment by jesicarson** [comment]
Methods: https://docs.google.com/document/d/13_UydUmbxQmFawWRZsXoWXkI02ubnrD45Cqf66y1uMY/edit

Organizations: 
https://docs.google.com/document/d/1nW_T7H6FigWq34HqR24_nuRZl7Nc6fzT82z90KC5qk4/edit

Note - @ascott these are still "draft" . I'm going to review/update them now and will change the doc name to "Final" when they're ready to roll out. 

Question - do the labels have to match the text used in the form exactly? or can these be slightly different? youll see a question from pat about this in the methods doc. thanks!

**Comment by ascott** [comment]
@jesicarson do you mean the labels for the fields in the dropdown or for the chip section labels?

**Comment by jesicarson** [comment]
fields in the drop downs. i tagged you in the question pat posed. 

@plscully can you review the draft docs? i made some suggestions and comments. thanks!

**Comment by ascott** [comment]
the labels for the fields in the dropdown are using the same labels as used on the reader view for the fields, so ideally we don't change those so we can keep them consistent. it does introduce some more complexity/duplication to implement different labels for only some fields in the search filters, rather than using the same labels as used on the reader view. i think from a user perspective it makes the most sense to keep these the same as well.

**Comment by jesicarson** [comment]
Thanks @ascott . Lets keep the same labels. I see pat's point about context given there is no explanatory text for search filters. But i agree it should match the reader view (which also lacks explanatory text, so it should be fine if its fine on the reader).

**Comment by jesicarson** [comment]
Also, here's the Case search filters file, so we have them collected. And I we'd also like to update the label of the first chip from Overview to Issues (or Issues & Topics, if we add "specific topics" to the list of search filters available for that chip): https://docs.google.com/document/d/1hhm7o9olglAj9m5YqdcT2JwTFezCMoEKufvR74yhQEw/edit

**Comment by jesicarson** [comment]
@ascott other than a long list of values, do you see problems with filtering by actual method entries for cases? ie if the "process" chip for cases included the entries for methods on ppedia (not the general types of methods). I'm probably not considering something here...

**Comment by ascott** [comment]
other than it being a really long list in the ui, i don’t think it would be
a problem to filter cases by method. @dethe do you see any issues with
this? in terms of the ui, maybe we could use the auto complete component to
select a method to filter by...

**Comment by dethe** [comment]
So we'd have a drop-down of all methods and allow filtering cases by which methods they linked to? That is do-able, but not as straightforward as our other filters to date.

**Comment by jesicarson** [comment]
I'm not sure if we need to do this for sure or not, for now I'm just checking to see if its possible. Thank you!
