### ISSUE TITLE
Teaching Page Updates (DRAFT)

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#677]
Hi folks. Just awaiting feedback from the teaching committee on [this draft text](https://docs.google.com/document/d/1trJG6BUHqb2Cdb0ZhO5C2F7X8lvvmCzOc6v-b5gWw7A/edit?usp=sharing), but thought I'd do a mockup of it to get a better sense of things. Here it is for comments and I'll make any updates before this goes live into the priorities list. Thanks!

![Teaching Page Mockup July 15 2019](https://user-images.githubusercontent.com/13560530/61257277-3bc67080-a725-11e9-9aa0-b50989ed9a83.jpg)

**Comment by ascott** [comment]
@jesicarson here is a PR for this new page: https://github.com/participedia/api/pull/700
did you feedback from the teaching committee yet?

**Comment by jesicarson** [comment]
@ascott awesome! ill just review that pr page quickly but otherwise we're good to go. The feedback from the team was more related to the form and was quite minimal. they're happy with this solution for now.

**Comment by ascott** [comment]
@jesicarson this is on prod now

**Comment by jesicarson** [comment]
Thanks @ascott looks great!
