### ISSUE TITLE
Add Language Drop Down to Reader (above 'Data' on desktop, above 'CASE' on mobile)

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#678]
Thoughts on this placement?

![Screen Shot 2019-07-15 at 5 29 14 PM](https://user-images.githubusercontent.com/13560530/61257500-2a319880-a726-11e9-9381-470e551c14fd.png)

**Comment by ascott** [comment]
i like this, but ,maybe feels a bit weird with the social icons between it and the main content... how would it work for mobile screens?

an alternative option is above the content in the main/center column, which works well for desktop and mobile screens:

<img width="1280" alt="Screenshot 2019-07-16 17 08 04" src="https://user-images.githubusercontent.com/130878/61338003-6fb89900-a7ec-11e9-94e7-3632ba33b0e2.png">
<img width="544" alt="Screenshot 2019-07-16 17 08 21" src="https://user-images.githubusercontent.com/130878/61338005-721af300-a7ec-11e9-82a8-9b58b0eea972.png">

**Comment by jesicarson** [comment]
That’s not quite working visually either, we are aiming for clean typography for the reader. But it might work down below the submitted by text, above the narrative? 
That said, the visual design of the white drop down field also looks nicer / cleaner on the black background of the footer, and feels a bit out of place on the white reader page.. are we sure a truncated version on the black top nav bar won’t work? The abbreviations for most of our supported languages are pretty clear, En, Fr, etc.. Plus if you change it from the default En to your language, you’d likely understand the abbreviation, right? And the drop down menu, when open, would list the full language values (English, French, etc), not just abbreviations.

**Comment by jesicarson** [comment]
Second guessing the placement in the top nav bar, as beside the white quick submit button it gets confusing.

How about this for desktop? And on mobile it could be at the top, as you show in your screenshot above. 
![Screen Shot 2019-07-17 at 1 03 51 PM](https://user-images.githubusercontent.com/13560530/61407802-73532b00-a893-11e9-9380-0217da69d69a.png)

**Comment by jesicarson** [comment]
Also, sidebar... @ascott can you let me know if its a lot of work to fix the alignment of the columns to match the design spec? As you can see if you compare your desktop reader screenshot to mine, the centre (media/narrative) column should be aligned with the search bar, possibly a little wider and closer to the data sidebar than it is currently. There are issues for this in usersnaps, but not P1 yet as I've been trying to hold off on non urgent stuff ;P

**Comment by ascott** [comment]
yeah i like it better over in the left hand data column as well. let's go with that. adjusting the columns isn't a lot of work, sorry i missed that! i can get that change in with the language dropdown PR.

**Comment by jesicarson** [comment]
Ok deal!
That column adjustment would also be awesome, thanks! Keep in mind on the homepage grid, the centre two columns are the same width as the narrative/media column on the reader. And on both homepage and reader views, these centre columns should align with the search bar.

**Comment by ascott** [comment]
@jesicarson this is on prod now. I'm almost done with the column adjustment, but it's taking a bit longer than expected, should have to done tomorrow.

**Comment by jesicarson** [comment]
@ascott great! just tested reader lang drop down on prod and filed a bug usersnap tho (it doesn't seem to be working, just reloads english).
And thanks for making the column adjustments!
