### ISSUE TITLE
Lazy loading images / videos

### ISSUE THREAD

**Issue by dethe** [participedia/api#716]
We can load pages faster if we don't load a bunch of huge images that the user may or may not see. There are two main approaches (and we should do both):

1. Pre-process images on AWS to have them available in different sizes, use responsive image technique to only load a size appropriate for the page and device.
2. Use a tiny placeholder for the image, load the real image only when user scrolls it into view.

Both techniques are covered well in this article: https://css-tricks.com/tips-for-rolling-your-own-lazy-loading/

**Comment by ascott** [comment]
👍  to lazy loading. related issue here for pre-processing images: https://github.com/participedia/api/issues/285
