### ISSUE TITLE
[DEV] admin-only field to flag 'Stub' entries

### ISSUE THREAD

**Issue by ascott** [participedia/api#765]
Allow entries to be marked as 1 of 5 completeness levels:

**Stub** = entire narrative is missing OR the entry is missing enough information to constitute an entire classroom assignment's worth of work to complete
**Partial (content)** = has about 50% of its narrative OR the entry is missing enough information to constitute HALF a classroom assignment's worth of work to complete.
**Partial (citations)** = an entry that is missing all citations (footnotes) but is otherwise complete (ie. would not make a good classroom assignment b/c the only things to add are references)***
**Partial (edits)** = an entry that needs significant improvements to its grammar/spelling. Can be any level of completeness.
**Complete** = anything above partial. Contains enough information to know what went on, and too much information to constitute half a classroom assignment.

Design issue and more discussion: https://github.com/participedia/api/issues/701

### Backend Work for @paninee 
**Database** 
- [x]  for each of these entry types `['cases', 'organizations', 'methods']`
- [x]  add a field called `completeness` which can accept 1 of the following keys
`['stub', 'partial_content', 'partial_citations', 'partial_editing', 'complete']`

**Views**
- [x]  the `completeness` field should be passed with other entry data on the following pages/views
    - home/search page
    - reader page
    - edit form page

**Updating**
- [x]  when the `completeness` field is passed (with one of the accepted keys) to the update action in the controller it should be saved
- [x]  only admin’s can update this field
- [x]  if an empty string or null value is passed, delete the currently saved value

**Filters (cases only for now)**
- [x] allow filtering on the `completeness` field
- [x]  the following url should return only entries marked as stubs https://participedia.net/?selectedCategory=case&completeness=stub (and for each of the other completeness keys)
- [x] allow multiple filters on the `completeness` field. The user may filter for both 'stub', 'partial_content', for example.

### Frontend Work for @ascott 
**Views**
- [x] on reader view, add user prompt with link to edit form for article - 
design: https://github.com/participedia/api/issues/701#issuecomment-539133938
- [x] on edit view, for admins only add select field with completeness options  - design: https://github.com/participedia/api/issues/701#issuecomment-538694054

**Updating**
- [x] pass completeness field up with the rest of the entry data to be save

**Filters (cases only for now)**
- [x] add filter option to list of filters, add Completeness as it's own pill

**Comment by ascott** [comment]
@paninee let me know your thoughts on this breakdown and if you have any ideas to improve how we do this!

**Comment by ascott** [comment]
@paninee i've started a branch this feature. let's both work off this branch, or feel free to work on another branch and submit a PR against this branch: https://github.com/participedia/api/compare/master...feature/stub-completeness-flags

**Comment by jesicarson** [comment]
Note: @scottofletcher will draft the text for these 5 states values in the drop down menu [in this document](https://docs.google.com/document/d/1IS2KpwfADTyzkOc3yCzIG2xPdFomS9mW__Ire4e6P04/edit?usp=sharing).

**Comment by jesicarson** [comment]
@scottofletcher  -  as I'm drafting copy for the modal pop ups, it occurred to me that there may be scenarios when an entry can require citations / footnotes AND improvements to grammar / spelling at the same time... does that mean a case could have 2 prompts on the top? does this happen often?

**Comment by scottofletcher** [comment]
@jesicarson yes good point, that does happen sometimes, and when it does, we tend to leave it up to the editor's discretion. I tend to use the grammar/spelling prompt in these cases, since it's kind of vague (I tried to write it so it wouldn't sound pejorative since some entries w/bad grammar are entered by our ESL partners). in cases where it's a partial (less than 50% of its narrative) and has bad spelling/grammar and/or is missing citations, I just use the partial prompt (ie. 'the following entry is incomplete...etc').

**Comment by jesicarson** [comment]
sorry @scottofletcher can you post the above comment in the design issue? thanks, i realized i should have done that and moved my comment there  - https://github.com/participedia/api/issues/701#issuecomment-540245431

**Comment by jesicarson** [comment]
@ascott while you're in there, please change the "Overview" chip to read "Issues"

**Comment by ascott** [comment]
@paninee can you please link me to the branch you've got the backend work in? i'd like to pull it into my front-end branch to test the flow end to end. thanks!
