### ISSUE TITLE
Entry cards on homepage - match labels to how we are sorting the cards

### ISSUE THREAD

**Issue by ascott** [participedia/api#770]
we currently sort the entry cards on the home/search page first by showing all featured entries, then by the last updated date, however we display the submitted date on the card which i think is confusing.

for clarity, i think we should do either of the following:
1. replace the Submitted date with the Updated date on the entry card
2. keep the Submitted date on the card and Add the updated date

thoughts @jesicarson @scottofletcher ?

![Screenshot 2019-10-16 12 57 57](https://user-images.githubusercontent.com/130878/66954655-af726500-f015-11e9-818f-91f74ad10f45.png)

**Comment by ascott** [comment]
@jesicarson ok, yes, that's what i thought the decision was as well, but i saw a few comments on another issue as well and wanted to confirm that was in fact the decision. thanks!

**Comment by jesicarson** [comment]
found it https://github.com/participedia/api/issues/701#issuecomment-539691685
so ya lets go ahead with that.
