### ISSUE TITLE
[DEV] Add author transparency to entry reader views

### ISSUE THREAD

**Issue by ascott** [participedia/api#789]
TODOs for @paninee 
- [x]  pass author/edit history data to view from controller for cases, methods and orgs
---- i'm thinking we will want to pass a key on the `article` object called `edit_history` which contains an array of objects representing each edit over time. each object should contain the user id, user name and timestamp.

```
article: {
  edit_history: [
    {
      user_id: 1,
      user_name: 'Scott Fletcher',
      timestamp:  '2018-03-05 22:14:46'
    },
   ...
  ]
}
```

TODOs for @ascott 
- [x] render list of edits in an accordion 

![image](https://user-images.githubusercontent.com/130878/69276334-2362d880-0b93-11ea-8ffb-1ee8856595b7.png)

**Comment by ascott** [comment]
also remove author info and use Entry history as source of truth for edits

**Comment by jesicarson** [comment]
What do you think about "Wiki Entry History" as the title? or "Wiki Contributor History" ... actually I like "contributor" better than "entry", as it is more clear. So even if we don't use "wiki" lets go with "Contributor History"

**Comment by ascott** [comment]
i like either "Wiki Contributor History" or "Contributor History". Your call @jesicarson !

**Comment by jesicarson** [comment]
blaaahhh! i dont know! ok let's go crazy and try "Wiki Contributor History" and see what people say :P

**Comment by paninee** [comment]
Completed the API task
