### ISSUE TITLE
Need to be able to restrict payloads of search to small # of fields

### ISSUE THREAD

**Issue by davidascher** [participedia/api#79]
In the map display, I need to be able to efficiently get all of the title + locations of _all_ of the cases for example, but without fetching body, and all of the other metadata on cases.

This will be a frequent query, as it'll happen on the home page.  I suspect we want a simplified version of `search_cases.sql` etc which only returns fields we know we need.  A hackier version is to do the full SQL search, but trim the results before they go over the slow wire.

Fields to return for search results:

* [ ] id
* [ ] title
* [ ] type (case/method/organization)
* [ ] lead image
* [ ] last updated
* [ ] (original) author name
* [ ] (original) author id
* [ ] bookmarked by current user?

**Comment by davidascher** [comment]
I dealt with this with `/search/map` so I don't need it urgently.

**Comment by dethe** [comment]
Generally for search results, what fields do we need? My best guess:

* id
* title
* type (case/method/organization)
* lead image
* last updated

Does that look right?

**Comment by davidascher** [comment]
Author name and id would be good too.  And bookmarked by current user or not.

**Comment by dethe** [comment]
Cool, thanks!

**Comment by dethe** [comment]
Oh, original author, most recent edited by, or both?

**Comment by davidascher** [comment]
Ah. Hmm.  never mind.  The mockup don't need it now, so let's assume we don't need them later. YAGNI.

**Comment by dethe** [comment]
Fixed, for full-text searches, in issue #83. Faceted search will fix this as part of #60 and/or #53
