### ISSUE TITLE
Set images to zoom and fill display on reader view image slideshow

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#791]

**Comment by jesicarson** [comment]
and also remove the slideshow of mini thumbnails below the main image. this gives us more vertical space if the main image needs to be a bit taller (maybe add 20-30px height?) to accommodate a wider variety of images.

**Comment by ascott** [comment]
@jesicarson i'm not sure this is the best solution, as images that have a portrait aspect ratio don't display well like this. 

eg: current styling
<img width="922" alt="Screenshot 2019-12-01 10 43 48" src="https://user-images.githubusercontent.com/130878/69918516-bf100680-1427-11ea-9e07-8a8bdd02c946.png">

eg: set to fill container
<img width="922" alt="Screenshot 2019-12-01 10 42 24" src="https://user-images.githubusercontent.com/130878/69918518-c1726080-1427-11ea-8266-00ee38a646fe.png">

what do you think about this alternative, where we give the container a background color? i think preserving the aspect ratio of the images is important.
<img width="922" alt="Screenshot 2019-12-01 10 48 20" src="https://user-images.githubusercontent.com/130878/69918553-304fb980-1428-11ea-94aa-8b381d2534f3.png">
<img width="923" alt="Screenshot 2019-12-01 10 48 33" src="https://user-images.githubusercontent.com/130878/69918554-32197d00-1428-11ea-9456-c217cb2832e2.png">

**Comment by jesicarson** [comment]
Interesting, the aspect ratio is really narrow, horizontally. would it help to make it taller? And, is the example zooming in to the centre of the image? looks like it might be zooming to the top of the image, rather than the centre. 

the current styling is better than the grey box anyway. and it does help to remove the thumbnails below.

**Comment by ascott** [comment]
@jesicarson the positioning of the image in the container was at the top, and not the center. it does work better if the image is centered in the container. 👍 

how is this looking to you?

![participedia-image-carousel-styling](https://user-images.githubusercontent.com/130878/70006394-c287b880-1521-11ea-896f-046564da259d.gif)

**Comment by jesicarson** [comment]
Better, but I’d still increase the height of the container a bit to make it more of a standard ratio (4:3 ish)

**Comment by ascott** [comment]
4:3 aspect ratio feels really big to me, what do you think?
<img width="1680" alt="Screenshot 2019-12-03 10 25 14" src="https://user-images.githubusercontent.com/130878/70078244-3031f400-15b7-11ea-8a74-930ee102bf06.png">

here is a 16:9 ratio: 
<img width="1680" alt="Screenshot 2019-12-03 10 25 40" src="https://user-images.githubusercontent.com/130878/70078264-3922c580-15b7-11ea-875d-6a3dc4c27d8b.png">

**Comment by jesicarson** [comment]
16:9 looks good!
