### ISSUE TITLE
Improve TTFB on home/search page

### ISSUE THREAD

**Issue by ascott** [participedia/api#792]
Our TTFB on the home/search page is currently 4.39s. Are there any optimizations we can make on the server and db queries to improve this?

<img width="1680" alt="Screenshot 2019-11-29 09 44 42" src="https://user-images.githubusercontent.com/130878/69884372-f72f1200-128c-11ea-8481-7ba0f22164ec.png">

**Comment by paninee** [comment]
i added index on the `things` and a few tables, i cannot verify on live yet, but upon testing it to my local. These are the results in my local without and with index.

![image](https://user-images.githubusercontent.com/29439995/70164582-46eb5000-1676-11ea-85c5-4e31c8b147b6.png)



I pushed changes to https://github.com/participedia/api/tree/pan-792

**Comment by paninee** [comment]
Tested on staging. The indexes seems to be helpful.

![image](https://user-images.githubusercontent.com/29439995/70460124-78935b00-1a6a-11ea-9241-42cbb717c42c.png)

**Comment by paninee** [comment]
@ascott when you have a moment can you try it out, be a second set of eyes, see if it's actually faster? Thanks!

**Comment by ascott** [comment]
@paninee thanks for this, looks great!! let's ship to prod!

**Comment by paninee** [comment]
@ascott the code is already on master. We have to run the migration script. But I'm stuck running it from Heroku.

**Comment by paninee** [comment]
Deployed on production
