### ISSUE TITLE
Add selected search filters to results text on homepage (so it's clear what has been selected)

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#803]
ie: https://participedia.net/?selectedCategory=case&query=women&method_types=collaborative
would display:
1 - 9 results of 9 for "Women" with filter: Collaborative Approaches (page 1 of 16)

**Comment by jesicarson** [comment]
another example (without a previous text query):
https://participedia.net/?selectedCategory=case&collections=coady_students
would display:
1 - 20 results of 20 for filter: Coady Institute Graduates (page 1 of 1)

**Comment by jesicarson** [comment]
another example (multiple filters selected):
https://participedia.net/?selectedCategory=case&general_issues=environment&country=Canada
would display:
1 - 20 results of 21 for filters: Environment, Canada (page 1 of 2)

**Comment by ascott** [comment]
@paninee can you take this one please?

**Comment by paninee** [comment]
Completed on this branch https://github.com/participedia/api/tree/pan-803. Will merge to `master`, deploy and test on stage.

**Comment by jesicarson** [comment]
@paninee great! Let me know when it’s on stage so I can test too. Thx! And if you could post a link to the staging site here so I can easily open on my phone that would be great. Cheers!

**Comment by paninee** [comment]
@jesicarson staging is on https://ppedia-stage.herokuapp.com

**Comment by jesicarson** [comment]
@paninee not seeing it on mobile? Screenshot on staging shows issues/arts and culture filter but no results text:
![EC5C8746-F49D-45BF-A2FF-26E5DA49AF79](https://user-images.githubusercontent.com/13560530/71381988-d8215880-258a-11ea-84c4-878da8ede91d.png)

**Comment by jesicarson** [comment]
Oh sorry is it not love yet? Lol

**Comment by paninee** [comment]
@jesicarson it's on staging https://ppedia-stage.herokuapp.com now. Not back then. sorry, should've been clearer.
