### ISSUE TITLE
add new collection: LATINNO

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#804]

**Comment by ascott** [comment]
@paninee can you take this one please?

a new collection can be added by adding the key to this array:
https://github.com/participedia/api/blob/master/api/helpers/shared-field-options.js#L2

and then adding the key/value to all of our locales files. i don't think there would be translation for this collection name, so it can be added to all locale files like this:
https://github.com/participedia/api/blob/master/locales/en.js#L773
"name:collections-key:latinno": "LATINNO"

**Comment by ascott** [comment]
@paninee i can take this one :)

**Comment by ascott** [comment]
@jesicarson this is on prod now.

**Comment by jesicarson** [comment]
@plscully FYI

**Comment by plscully** [comment]
great! thank you!
