### ISSUE TITLE
Review and fix migrate* commands in package.json

### ISSUE THREAD

**Issue by ascott** [participedia/api#810]
The following commands are throwing errors when run on heroku. @paninee can you please investigate and fix these commands?

`migrateprod`
`migratestage`

**Comment by zphingphong** [comment]
Have to merge this branch (https://github.com/participedia/api/tree/pan-810) into `master`, and I think it would make no sense to work on a branch for this task. Since the code needs to be on `master` in order for staging to pick it up, and we need to test on stage.

**Comment by zphingphong** [comment]
Fixed as discussed in https://participedia-team.slack.com/archives/GN63JSWBS/p1579067727039600
