### ISSUE TITLE
[DEV] Selected search filters 

### ISSUE THREAD

**Issue by ascott** [participedia/api#825]
- [x] remove selected search filter text from results text and revert to this format `1 - 20 results of 36 (page 1 of 2)`
- [x] add selected serach filters badges with `x` icon to remove search filter. when the `x` is clicked the url should be updated to reflect the removed filter and the page reloaded to update the search results

![image](https://user-images.githubusercontent.com/130878/72285078-450e9800-35f7-11ea-90e6-71449cb89308.png)

design issue for reference: https://github.com/participedia/api/issues/821

**Comment by zphingphong** [comment]
The changes are in https://github.com/participedia/api/tree/pan-825. Ready for PR review.

**Comment by zphingphong** [comment]
![image](https://user-images.githubusercontent.com/558198/72497717-2c160a80-37e2-11ea-9af3-3b0636a10d8b.png)

![image](https://user-images.githubusercontent.com/558198/72497863-96c74600-37e2-11ea-88c0-661cf201549f.png)

**Comment by paninee** [comment]
![image](https://user-images.githubusercontent.com/29439995/72919140-cbb02d00-3cfb-11ea-9b61-fa63f1727dc6.png)

**Comment by jesicarson** [comment]
@paninee looks good on staging. we can ship this to prod. thanks!
FYI, Amber had a few design thoughts on how we can further improve this in a future iteration, I'll post that in the design issue and we can re-open later on. Not a priority, as this solution is great for now.

**Comment by zphingphong** [comment]
On production

![image](https://user-images.githubusercontent.com/558198/72948692-c3c3ad80-3d3a-11ea-9064-31ef31db5518.png)
