### ISSUE TITLE
TODO: Review and list all paid subscriptions/dependencies

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#840]
Need a list of accounts, as we aim to phase Pat's credit card out. We can list them here and check them off when its sorted. 

Website related accounts:
- [ ] AWS
- [ ] Heroku
- [ ] Google
- [ ] ? anything else

Non website accounts:
- [ ] Zoom
- [ ] SurveyMonkey
- [ ] Mailchimp
- [ ] ?

**Comment by plscully** [comment]
- User Snap
- Name-Cheap -- re: the domain name registrar for www.participedia.xyz (I think the last time I paid this was in summer 2018)
- JoinMe / Logme in -- I haven't seen a bill for this since June 2017
