### ISSUE TITLE
[DESIGN] Move 'Collections' to the top level of the entry type tabs

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#864]
Jesi will post mockups here

- need to also discuss adding a collections field for methods and orgs.

**Comment by jesicarson** [comment]
In this version of the idea, we'd add a drop down for collections beside the entry type tabs (always visible on 'all,' as well as each of the tab types when selected). This drop down navigates users to a new page which is the "collections page" for that collection (essentially a search filter, but results with custom page display). That page would give more metadata about the collection (title, description, link to external site) possibly in place of the map, and also display the entries for the collection. probably need to be able to use the search filters for large collections. might display differently from the typical homepage results? featured entries for the collection? design tbd. 

![CollectionsUPScreen Shot 2020-03-03 at 1 45 16 PM](https://user-images.githubusercontent.com/13560530/75822819-741ecb80-5d55-11ea-9270-9bf462610542.png)

**Comment by jesicarson** [comment]
precedent of landing page/functionality embedded into another site. white labelled. https://www.decidim.barcelona/

**Comment by jesicarson** [comment]
different aesthetic:

![Screen Shot 2020-03-13 at 2 06 32 PM](https://user-images.githubusercontent.com/13560530/76659569-041dfb80-6534-11ea-92e3-b136a0680db2.png)

![Screen Shot 2020-03-13 at 2 06 51 PM](https://user-images.githubusercontent.com/13560530/76659571-084a1900-6534-11ea-9ab9-a91e37ce86ba.png)

**Comment by jesicarson** [comment]
Thinking about what it would look like if each collection had a map "slider" ... this is not fully thought through yet, but as an example could easily be populated by fields for: Title, Description, Button Text and Button URL. 

![Screen Shot 2020-03-13 at 4 42 32 PM](https://user-images.githubusercontent.com/13560530/76669638-c7f59580-6549-11ea-8a43-e1de779c63dd.png)

**Comment by jesicarson** [comment]
Another way to deal with collections is to treat it the same way as the cases, methods and orgs tabs, and then display each collection as a card, with the title and metadata about how many entries are included in the collection (clicking the card would then lead to the landing page), also if you used List View, you could read the descriptions for the collections all in one place. Here we can have a featured collection, as well as bookmark a collection. 

![Screen Shot 2020-03-30 at 12 36 12 PM](https://user-images.githubusercontent.com/13560530/77954211-2a0d0500-7283-11ea-9b5e-010bfa327e4d.png)

**Comment by jesicarson** [comment]
Example GOC landing page
- title
- description (280 char max)
- 1 link
- 1 banner image
- do not show search filters for collections with less than 20 results, but do show tabs to allow filtering by entry type 
- (TBC the collections tab disappears on landing pages @ascott - thoughts?) 
- (TBC scrolling to left or right in the banner image could load the next collection)

![Screen Shot 2020-03-30 at 12 48 40 PM](https://user-images.githubusercontent.com/13560530/77955309-cc79b800-7284-11ea-9b2e-c89b291c2ccc.png)

**Comment by ascott** [comment]
>(TBC the collections tab disappears on landing pages @ascott - thoughts?)

yes, agreed


> (TBC scrolling to left or right in the banner image could load the next collection)

i think we should remove the arrows in the banner image, and just rely on collections tab on the home page to access collections

**Comment by jesicarson** [comment]
Another mockup for landing pages (more like a profile page) for consideration. 

![Screen Shot 2020-03-30 at 2 43 24 PM](https://user-images.githubusercontent.com/13560530/77964979-f4711780-7294-11ea-968e-9e8c37d02f8e.png)

**Comment by jesicarson** [comment]
And another, just food for thought - trying to connect the entry type sorting tabs to the collection information. could be that we don't even want to filter collections by type at all. 

![Screen Shot 2020-03-30 at 3 03 16 PM](https://user-images.githubusercontent.com/13560530/77966308-9abe1c80-7297-11ea-96e3-829115d92b0a.png)

**Comment by jesicarson** [comment]
ie: without any tabs or filters:

![Screen Shot 2020-03-30 at 3 07 22 PM](https://user-images.githubusercontent.com/13560530/77966582-2c2d8e80-7298-11ea-8ac9-c18986b447ca.png)

**Comment by jesicarson** [comment]
And here's one that looks like a case, with results below the short description (would also allow for multiple images, and links)

![Screen Shot 2020-03-30 at 3 29 42 PM](https://user-images.githubusercontent.com/13560530/77968099-53d22600-729b-11ea-91a4-4817f17618d7.png)

**Comment by jesicarson** [comment]
After chatting with Amber, adding a vertical separator between the organizations and collections tab, to visually differentiate them subtly. We agree adding collections to the tabs with cards for collections that then lead to the landing pages is a nice solution. 

Also showing possible updates to the homepage map overlay for review with Amber today. the idea is there would be some automatic transition/animation/slider/fade or something between the very explicit tagline, and the mission statement - the new [+ entry type] buttons would all remain in place. 

![Screen Shot 2020-04-02 at 10 19 47 AM](https://user-images.githubusercontent.com/13560530/78279169-fb359f80-74cb-11ea-86a7-3d80d88c9de6.png)

![Screen Shot 2020-04-02 at 10 19 58 AM](https://user-images.githubusercontent.com/13560530/78279179-fec92680-74cb-11ea-9cf6-cab408622308.png)

**Comment by jesicarson** [comment]
also, updated the GOC collection overlay example 

![Screen Shot 2020-04-02 at 11 13 11 AM](https://user-images.githubusercontent.com/13560530/78283724-135ced00-74d3-11ea-9bda-bc9dc2dc93f7.png)

**Comment by jesicarson** [comment]
Here's a [Google Doc](https://docs.google.com/document/d/1uIuWBCDn0mVb4_y-0GcumuBDFm-CLtew0bDs1oHPYlk/edit?usp=sharing) to plan the text for the map overlay slideshow/marquee. @plscully

**Comment by jesicarson** [comment]
@ascott per our call today - updated spec for landing pages to include text link to "View All Collections" which would take the user to the homepage collections tab. this is obvious im sure but just want to also flag that the link button should have 2 fields in the entry form - one for the url, and one for the custom button text. i'll start finding better banner images for the collections we have so far too. thanks!

![Screen Shot 2020-04-08 at 2 06 15 PM](https://user-images.githubusercontent.com/13560530/78833877-7a324880-79a2-11ea-9ebd-c71f3a365bb3.png)
