### ISSUE TITLE
[DEV] Translation of user generated text

### ISSUE THREAD

**Issue by ascott** [participedia/api#868]
Overview doc: https://docs.google.com/document/d/121UEkZNXQyn9wVO4aw96CCuhjEmAASl9lXAChIHicDU/edit#

### User flows
**A new entry is added**
- a user adds a new entry and the original language is saved as the language they are viewing the site in (this is already done)
- [x] [pan] when it is saved, the user entered text fields (title, description, body) is machine translated in to our other languages, from this point the user entered text is forked, and different versions exist for title, body, and description for each language. 
----  `title`, `description`, `body` fields are saved in a table called `localized_texts`. this table already exists

**An entry is edited in its original language**
- no changes needed

**An entry is edited in another language**
- [x] [alanna] an alert is shown that says “This entry was originally added in {original_language}. [link]View this entry in {original_language}.”
- [x] [jesi] draft copy for info modal
---- Entry saved for 1st time it is machine translated into these languages
---- Each language is a version, but they share the same data (title description and body are different versions)
- [x] [pan] `title`, `description`, `body` fields on the entry object are pulled from the `localized_texts` table in the language being viewed, not in the original language
- [ ] [nice-to-have/future feature (alanna & pan)] if a user is editing an entry in a language that is not the original language, and the original language has a description/or body saved, add a prompt/button above respective input/textarea -- "Update this field with a machine translation from the original language". If the additional language version has some content in either description/body, this button is not shown.

**An entry is viewed in its original language**
- no changes needed

**An entry is viewed in a language that is not it’s original language**
- [x] [pan] The title, description, body fields on the entry object are pulled from the localized_texts table in the language the site is being viewed in
- [x] [alanna] an alert is shown that says “This entry was originally added in {original_language}. [link] View this entry in {original_language}.”

**Other tasks**
- [x] [pan] node script to machine translate all existing entries user generated fields (title, description, body) and save to `localized_texts` table. `localized_texts` contains versioned entries 
- [x] [pan] Make sure not to run the script twice on the whole set of data (expensive)
- [x] [alanna] spin up a new localization-staging server and database so we can work and test this project independently of our current staging server.  done: https://participedia-i18n-staging.herokuapp.com/
- [x] [pan] Think about where should google json file should be so that it isn’t exposed.
- [x] [pan] Accept language short code in the URL. This should switch the user's language. For example if the URL is https://participedia.net/case/de/5600, this should set the user's language to German, https://participedia.net/case/fr/5600 => French
- [x] [pan] write an initial rollout plan

**Comment by ascott** [comment]
**currently in progress:** [pan] node script to machine translate all existing entries user generated fields (title, description, body) and save to localized_texts table. localized_texts contains versioned entries

**Comment by paninee** [comment]
@ascott i've completed my part of the checklist. Is this ready to go to stage or are we waiting for your feature to be completed before we test it there?

**Comment by jesicarson** [comment]
Drafting modal text here: https://docs.google.com/document/d/1F6CeUeuh-uah7q4-JeU_F44ni1isrpUwjXSqlafa4aI/edit?usp=sharing

**Comment by ascott** [comment]
@paninee thanks for your work on this!! i will do my work on this branch and test on our i18n server before going to staging.

**Comment by paninee** [comment]
Rollout plan

1. Merge code to `master`, which will allow new entries to be translated.
2. We may want to test run that for a few weeks. Make sure it's stable.
3. Once the new entries translation has proven stable, increase the Translation API quota temporarily to run the script to translate existing data.
4. Run `scripts/generate-entry-i10n.js`

**Comment by ascott** [comment]
a couple more todos
- [ ] when a collection is added, it is not translated like a case, method and org is @paninee 
- [ ] add faq item @ascott

**Comment by ascott** [comment]
pre roll out todos:
- [ ] review PR comments and make small changes requests
- [ ] ensure all needed ENV variables are set on ppedia-stage and participedia-api app on heroku
- [ ] get tests passing on participedia-i18n-staging

roll out plan
- [ ] merge this PR into master https://github.com/participedia/api/pull/876
- [ ] deploy to staging
- [ ] run needed migrations on staging
- [ ] test on staging
- [ ] put prod into maintenance mode
- [ ] deploy to prod
- [ ] run migrations
- [ ] take prod out of maintenance mode
- [ ] test app functionality
- [ ] run script to translate all (non-hidden) entries
