### ISSUE TITLE
[DEV] Add landing pages for Collections

### ISSUE THREAD

**Issue by ascott** [participedia/api#897]
- [x] db migration to add new table for collections @paninee 
---- fields needed: title, description, links, photos (same field types as other entry types)
- [x] add collections controller @paninee 
- [x] add sql for create, update, delete collection @paninee 
- [x] add sql to list all new collections for new type @paninee 
- [x] add collections key to json returned for home/search page. for each collection in the array, the format should be:
```
{
  "id": 1,
  "type": "collection",
  "featured": boolean,
  "title": "Government of Canada",
  "description": "...",
  "post_date": "2017-10-26T17:00:00",
  "updated_date": "2020-03-30T17:00:00",
  "bookmarked": boolean,
  "photos": [
    {
    "url": "",
    "source_url": "",
    "attribution": "",
    "title": ""
    }
  ]
}
```
- [x] handle `query` search on the collections tab, so the results returned for this url: http://localhost:3001/?selectedCategory=collections&query=budget. I believe query searches title and description for cases/methods/orgs, so this would be the same for collections @paninee 
- [x] remove collections as a search filter for cases/methods/orgs @ascott 
- [x] migrate the existing collections column for cases/methods/orgs to point to the new collections table. currently we are storing an array of keys (ie: latinno or participedia_team) but now we will want to migrate to use the id of the collection from the new collections table @paninee 
- [x] create edit entry template @ascott 
- [x] create view entry page template @ascott 
- [x] add tab on homepage for Collections @ascott 
- [x] add `+ Collections` button to entry type chooser page `/content-chooser` (only admins can access this button/page) @ascott
- [x] make collections field on case, method, org pages admin only @ascott 
- [x] add static text to translation tool and update translations @ascott
- [ ] testing @ascott @paninee @jesicarson 
- [ ] running migrations and deploy @paninee 

<img width="1060" alt="Screen Shot 2020-04-09 at 4 20 38 PM" src="https://user-images.githubusercontent.com/130878/78949417-580ef800-7a80-11ea-80a4-fe692304d143.png">

![image](https://user-images.githubusercontent.com/130878/78949428-63622380-7a80-11ea-8ea5-0d8de08a3f08.png)

design issue: https://github.com/participedia/api/issues/864

**Comment by jesicarson** [comment]
@ascott only the top screenshot (with the pink spacing guidelines) is the one we're using. the bottom one that looks more like a case was just a test.

**Comment by ascott** [comment]
@jesicarson gotcha, thanks for clarifying

**Comment by paninee** [comment]
@ascott ready to be tested with your frontend code. Here are the steps to get the data migrated.

1. Run `npm migratelatest` - This will create `collections table` and update `search_index_en` view to include collections in search logic. RUN THIS FIRST
2. Run `scripts/collection-logic-adjustment.js`. This will store the existing collection records in the Collection table. It will update `collection column` in cases, methods and organization tables to use collection id instead. 

We need to make adjustments tot he frontend still.
- Localization of selected collection in edit/create cases, methods and organization are not yet done. But API return the collection object for display.
- Localization of collections in `view` of cases, methods and organization are not yet done. But API return the collection object for display.
![image](https://user-images.githubusercontent.com/29439995/79598313-95830f00-8098-11ea-81e5-cdf0bcce8f53.png)
![image](https://user-images.githubusercontent.com/29439995/79598325-9c118680-8098-11ea-90b3-afc418a5bb6a.png)

**Comment by jesicarson** [comment]
@ascott after design review with amber there are a couple things we think will improve users understanding of landing pages for collections, illustrated in the mockup below.
1. We would like the results text for landing pages to explicitly state the name of the collection, and how many entries are in it (showing the All tab in mockup, but would be updated for each of the tabs, ie, for the cases tab the results text would read: The Covid-19 Response Collection contains 15 Cases)
2. Change the homepage tab to read "All Collections" and keep the tab in place on landing pages (remove the "View all collections" link text from the overlay box). 
3. Please align the overlay box to the left, extend the box wider ~across 3 columns, and also use the font sizes specified in the mockup for the landing page type, title and description text.  
4. Anchor the link button to the bottom of the white overlay box (30px from bottom edge). 
Thanks! 
![Screen Shot 2020-04-24 at 4 20 01 PM](https://user-images.githubusercontent.com/13560530/80264270-752ef380-8648-11ea-882a-9a44e168239b.png)

**Comment by ascott** [comment]
@jesicarson thanks for this design update! i'll make these changes

**Comment by jesicarson** [comment]
Thanks Alanna! Also @ascott Sorry for leaving those straggler issues open, should have cleaned up my paper trail a little better after testing. 
We also were hoping you could weigh in on #1 above - is dealing with the results text that way manageable? It would also be nice for the results text on the homepage tabs to be treated more explicitly as well. I believe theres a usersnap to this effect. Maybe let’s chat about this on our call on weds. Thx!

**Comment by ascott** [comment]
@jesicarson no problem!  the first item above is doable, and shouldn't take long to add. 

i also noticed that the results text on the homepage is missing the search query in the results text. i added another usersnap to make sure it doesn't get overlooked again. i think we had this at some point, but i'm not sure when it got removed 🤔 we can add this back.

**Comment by jesicarson** [comment]
@ascott yes, i was wondering about that, noted it here during testing: https://github.com/participedia/usersnaps/issues/1030 (which I'll go ahead and close now)

**Comment by ascott** [comment]
@jesicarson the design review changes above are on staging now.
