### ISSUE TITLE
[DEV] Improvements to CSV download functionality

### ISSUE THREAD

**Issue by ascott** [participedia/api#942]
Currently we link to the csv download on the [Research](https://participedia.net/research) page, with the following links:

- Cases: https://participedia.net/?selectedCategory=case&returns=csv
- Methods: https://participedia.net/?selectedCategory=method&returns=csv
- Organizations: https://participedia.net/?selectedCategory=organizations&returns=csv

We would like to enable users to be able to download csv files from the search results page, and for the csv files to be generated based on the filtered search results. Currently the csv files contain all the data. It is to be decided where the links to the cvs files will live in the search results UI, but it would be great to get the backend work for this started so we can incorporate the csv downloads with the redesigned search results page.

The current code for generating csv files is here: https://github.com/participedia/api/blob/master/api/helpers/create-csv-data-dump.js. This should be updated to accept search filter params and to generate a csv of only the included search results.

**Comment by ascott** [comment]
@paninee let me know if you have questions about this or need more info. we can also discuss in our meeting tomorrow.

**Comment by paninee** [comment]
@ascott do we want to be able to download the collection as CSV as well?

**Comment by jesicarson** [comment]
Since we are aiming to be able to download any set of results, then I think: yes, collections should be able to be downloaded too (as they are basically a curated set of results). Do you agree @ascott ?

**Comment by paninee** [comment]
@jesicarson i think we talk about a different feature. At the moment, we can choose to download CSV for case, method and orgs. My question was whether or not the collection can be downloaded the same way, not the cases curated in particular collections.

**Comment by jesicarson** [comment]
Maybe @ascott can clarify.

**Comment by ascott** [comment]
I don't think we should include a csv download for collections, since the data structure there is different than for cases, methods and orgs. Collections include all three types of entries, and the data structure for each entry type is different, so it's not really possible to create 1 csv file that would contain all entries for a collection, since the header columns are different. 
 
One solution if it's important to be able to download data related to collections (is it important? or a nice to have?) is to include the collections search filter back to search filters for cases, methods and orgs. That way a user would be able to download 3 different csv files for entries contained in a collection.

Does that clairify @jesicarson? Let me know what you think @jesicarson @paninee

**Comment by jesicarson** [comment]
Thanks @ascott. Good point about multiple entry types. It's definitely a nice to have at this point, so let's leave collections downloading out of the scope of this project for now. @paninee does that answer your question?
