### ISSUE TITLE
Change "PhraseApp" to "Phrase" and update URL on about page

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#947]
From Phrase via email (@ascott looped in via cc):

Hi Participedia team,

We happily noticed that you link to our old website [here](https://participedia.net/about), but we moved to the new domain phrase.com (formerly phraseapp.com).

If you find a minute, we’d love you to update the link from currently https://phraseapp.com/?utm_campaign=phraseapp-homepage&utm_medium=partner-relations&utm_source=participedia to https://phrase.com/?utm_campaign=phraseapp-homepage&utm_medium=partner-relations&utm_source=participedia. So it’s just the domain that’s changed. We would also be very happy about an update of our brand name (now Phrase).

This would mean a lot to us! It might be that we’d have to switch off the old domain phraseapp.com eventually. 

Thanks a million for your time and support!

Cheers, 

Ida

**Comment by jesicarson** [comment]
@ascott can you prioritize this this week? would be good to write back to ida and say we've done it, since they're sponsoring us with a free account. thanks!

**Comment by ascott** [comment]
thanks for the reminder @jesicarson. i can do this
tomorrow

**Comment by ascott** [comment]
@jesicarson this is on prod now
