### ISSUE TITLE
Make Joyce Chen a site admin

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#952]
joycechen@mylfabc.ca

Joyce will be submitting entries to the OECD collection, and as a work around will unhide the collection each day, add entries, then hide it again. They have reasons for keeping it hidden until complete. Related to: https://github.com/participedia/usersnaps/issues/1104

**Comment by jesicarson** [comment]
@ascott please ping Pat when this is complete.

**Comment by ascott** [comment]
@jesicarson @pat we don't have an account for joyce with this email address but there is another joyce chen with the email joyceechen1011@gmail.com. if she would like to use this new email address, she will need to create an account before i can make her an admin.

**Comment by jesicarson** [comment]
Thanks @ascott 
I’ve emailed Joyce and cc’d you.

**Comment by jesicarson** [comment]
@ascott please go ahead and use that gmail account for Joyce. Thanks!

**Comment by ascott** [comment]
@jesicarson ok done, joyce is an admin now. :)

**Comment by jesicarson** [comment]
Gracias!
