### ISSUE TITLE
[homepage-redesign] search page frontend

### ISSUE THREAD

**Issue by ascott** [participedia/api#967]
edit search.html to 
- [x] revise pagination to match new mockups
- [x] remove old search filters ui
- [x] add more filters button that will trigger search filters modal
- [x] show a red badge with the number of selected filters in the button
- [x] add clear all link that unchecks all filters
- [x]  add show results button
- [x] create a countries autocomplete dropdown to filter results by country (i had originally used a Google Maps autocomplete in the mocks, but we don’t need that for filtering on country only.)
- [x] create a search-filter-list partial 
  - search filter name/header
   - 2 columns, only show 4 filters, with a Show all link to reveal the rest of the filters. we should be able make use of and extend our existing accordion partial/js for this behaviour. `accordion.css` and `accordion.html`. See `openAllAccordionsOnPage()` in `research-view.js`.
- [x] add search results summary text to search results pagination section
- [x] https://participedia-homepage-2020.herokuapp.com/search?selectedCategory=case&openFilters=1 should open the search  modal.
- [x]  add (download csv) button to search results page

![search filters modal with location dropdown](https://user-images.githubusercontent.com/130878/90293397-d584b380-de38-11ea-8494-a0d845626071.png)
![search filters modal with location set](https://user-images.githubusercontent.com/130878/90293400-d61d4a00-de38-11ea-935c-c39e0cf2e1c9.png)
![search filters modal](https://user-images.githubusercontent.com/130878/90293401-d6b5e080-de38-11ea-887d-005afff1c2f7.png)
![search results no search term no filters, advanced search](https://user-images.githubusercontent.com/130878/90293404-d74e7700-de38-11ea-9bd7-6fc04fde0fd9.png)
![search results no search term no filters, all tab](https://user-images.githubusercontent.com/130878/90293405-d74e7700-de38-11ea-82fd-1c0791a51bee.png)
![search results no search term no filters, cases tab](https://user-images.githubusercontent.com/130878/90293408-d87fa400-de38-11ea-93b5-e93efe8cb7fb.png)
![search results no search term no filters, methods tab](https://user-images.githubusercontent.com/130878/90293411-d9183a80-de38-11ea-848f-071fdff6e9d4.png)
![search results no search term no filters, o](https://user-images.githubusercontent.com/130878/90293412-da496780-de38-11ea-9b5b-904daf15954c.png)
![Search Results With Keyword Term And Filters Selected](https://user-images.githubusercontent.com/130878/90293416-db7a9480-de38-11ea-868d-a3e13f241376.png)
![search results with search term](https://user-images.githubusercontent.com/130878/90293419-dcabc180-de38-11ea-9517-971e58c02d85.png)

**Comment by jesicarson** [comment]
resizing issue
![Screen Shot 2020-09-03 at 3 17 40 PM](https://user-images.githubusercontent.com/13560530/92179036-c4581280-edf8-11ea-875a-0d6f26676b55.png)

**Comment by ascott** [comment]
thanks for your work on this @paninee, it's looking great! 
here is some feedback related the the filters.

- [ ] if a search filter is selected for a given section, open that section/accordion to being with. ie: if the search filter `Education` is selected in the `General Issues` section, so open that section when the modal opens

<img width="1552" alt="Screen Shot 2020-09-14 at 1 35 44 PM" src="https://user-images.githubusercontent.com/130878/93135571-65fc2100-f68f-11ea-8ac5-ac6770ad2782.png">

**Comment by jesicarson** [comment]
@paninee here's [an svg file](https://drive.google.com/file/d/1KSm66wzp_gf2iUgwDZqIIUGPduZFZ-s1/view?usp=sharing) of the new csv download button. below is a screenshot of its placement on the search page. When the button is clicked, a csv file of the full set of search results should automatically download (not just the 20 visible on the page, but all the results). The button should show up when the cases, methods, or organizations tab is selected (it should not be visible on the all tab or the collections tab). 

![Screen Shot 2020-09-16 at 2 51 32 PM](https://user-images.githubusercontent.com/13560530/93396206-1e5ecc00-f82c-11ea-86e5-07f751fb856c.png)

**Comment by paninee** [comment]
CSV download button done.
