### ISSUE TITLE
[homepage-redesign] create Getting Started page

### ISSUE THREAD

**Issue by ascott** [participedia/api#968]
remaining todos:
- [x] edit draft text in google doc
- [x] wrap phrases for translation
- [ ] record video
- [ ] embed video on page

draft text doc: https://docs.google.com/document/d/1vjKf6lQyP2jA6TYllfEhgRBiAyy91EUCuQqTTCHyH0k/edit

-----

Notes from last meeting on possible approach:
https://docs.google.com/document/d/16o5IL0jTnoYs6QcbNcT2hwt5eqqJSozdfNET10bTMb8/edit

Examples of getting started guides/pages
- https://en.wikipedia.org/wiki/Help:Getting_started
- https://docs.github.com/en/github/getting-started-with-github/quickstart

**Comment by jesicarson** [comment]
Quick visual scan of top Getting Started pages in google search:

![Screen Shot 2020-09-03 at 10 15 53 AM](https://user-images.githubusercontent.com/13560530/92147085-7a0e6b80-edcf-11ea-8ede-4152e352145c.png)
![Screen Shot 2020-09-03 at 10 16 18 AM](https://user-images.githubusercontent.com/13560530/92147093-7bd82f00-edcf-11ea-8352-58f89896518c.png)
![Screen Shot 2020-09-03 at 10 17 21 AM](https://user-images.githubusercontent.com/13560530/92147096-7c70c580-edcf-11ea-901f-f870012ccd9e.png)
![Screen Shot 2020-09-03 at 10 18 20 AM](https://user-images.githubusercontent.com/13560530/92147097-7d095c00-edcf-11ea-9f16-205dba343dae.png)
![Screen Shot 2020-09-03 at 10 18 32 AM](https://user-images.githubusercontent.com/13560530/92147101-7da1f280-edcf-11ea-951f-d9f1cb72b869.png)
![Screen Shot 2020-09-03 at 10 19 35 AM](https://user-images.githubusercontent.com/13560530/92147103-7da1f280-edcf-11ea-9af9-ffdec0d27879.png)
![Screen Shot 2020-09-03 at 10 20 26 AM](https://user-images.githubusercontent.com/13560530/92147105-7e3a8900-edcf-11ea-9eaf-b4fe051a5dc9.png)
![Screen Shot 2020-09-03 at 10 21 13 AM](https://user-images.githubusercontent.com/13560530/92147106-7e3a8900-edcf-11ea-8d95-e0a881018939.png)
![Screen Shot 2020-09-03 at 10 21 52 AM](https://user-images.githubusercontent.com/13560530/92147109-7ed31f80-edcf-11ea-911a-3cc86822045e.png)
![Screen Shot 2020-09-03 at 10 22 04 AM](https://user-images.githubusercontent.com/13560530/92147112-7f6bb600-edcf-11ea-98d3-8b4b721a5fac.png)
![Screen Shot 2020-09-03 at 10 22 22 AM](https://user-images.githubusercontent.com/13560530/92147115-7f6bb600-edcf-11ea-8603-8c1223e514c9.png)

**Comment by jesicarson** [comment]
I like twitter's approach of a very simple mix of suggested, and visual, "ways in" to the content, with a bit of easy onboarding as well. The other getting started pages are pretty technical, but as discussed we want to create a page where people can begin to themselves the Participedia community. This can link to the help/contact page - which we can also think about fleshing out as more of a "help centre" using tabs / table of contents sidebar to organize the FAQ's at some point down the line.

**Comment by jesicarson** [comment]
Here's a site with a similar framework to participedia, but even more complicated asks of users:

![Screen Shot 2020-09-03 at 10 29 44 AM](https://user-images.githubusercontent.com/13560530/92147914-9c54b900-edd0-11ea-8797-aa7ae5c593c0.png)
![Screen Shot 2020-09-03 at 10 30 12 AM](https://user-images.githubusercontent.com/13560530/92147926-a1196d00-edd0-11ea-833d-25db33f6bce0.png)
![Screen Shot 2020-09-03 at 10 30 28 AM](https://user-images.githubusercontent.com/13560530/92147933-a37bc700-edd0-11ea-8275-c1127ec00d44.png)

**Comment by ascott** [comment]
@jesicarson and i drafted copy for this page here: https://docs.google.com/document/d/1vjKf6lQyP2jA6TYllfEhgRBiAyy91EUCuQqTTCHyH0k/edit

i added the html template today with a placeholder video and the draft text. 

remaining todos:
- [ ] edit draft text in google doc
- [ ] wrap phrases for translation
- [ ] record video
- [ ] embed video on page

![screenshot-localhost_3001-2020 09 16-12_47_06](https://user-images.githubusercontent.com/130878/93385299-eac77600-f81a-11ea-8de6-322c60038538.png)
