### ISSUE TITLE
[homepage-redesign] finalize new content/copy for homepage

### ISSUE THREAD

**Issue by ascott** [participedia/api#969]
TODO: add link to google doc for homepage copy

**Comment by jesicarson** [comment]
@ascott can you give me an estimated deadline for when you might need this by? I will try to jump on it first thing next week! meep.

**Comment by ascott** [comment]
@jesicarson no rush on this! starting next week sometime works!

**Comment by jesicarson** [comment]
started a [gdoc](https://docs.google.com/document/d/1SVlhvpoJhN18gEmGCrDoO_RU_AxE2NjVcvGPJftMGPU/edit), i will ping you when it is populated

**Comment by jesicarson** [comment]
@plscully @amberfj do you want to [review the copy](https://docs.google.com/document/d/1SVlhvpoJhN18gEmGCrDoO_RU_AxE2NjVcvGPJftMGPU/edit?usp=sharing) for the new homepage before testing on staging? It may not be necessary before testing, but probably worth doing before we go live on production, and definitely before we ask for localization verification from our team on Phrase.

**Comment by plscully** [comment]
@jesicarson I will look at the copy shortly (today!) . . . BTW, have you made any significant changes to the design from what you shared a few weeks ago in this slide deck https://docs.google.com/presentation/d/1O8gSqmEt_ZR26GRYPvHxzXJ6tuYiOPiiMBYPHM1T7OY/edit#slide=id.p1

**Comment by jesicarson** [comment]
Thanks @plscully - no significant changes.

**Comment by plscully** [comment]
The homepage copy looks good! I didn't suggest any changes, though your question about linking to the guidelines led me to look at them and I tagged you with a few questions about them. I realize that's a separate project, but once you look at my questions I think we may be able to address them fairly easily.
