### ISSUE TITLE
[DEV] updates to CSV data downloads

### ISSUE THREAD

**Issue by ascott** [participedia/api#983]
These are changes needed to improve the format and quality of the CSV download files based on the recommendations from Verónica Hurtado in [this report](https://docs.google.com/document/d/1iFO88fUJ_P2iRTrlyRBoepIkpeabl1sPj0_mg0zlQu4/edit) and from discussion in the Sept 15 Data Management meeting [[agenda]](https://docs.google.com/document/d/11xvgrBG2l95m7CZITHaw7-R9fkWZ0xFJcuI-5HChmqY/edit).

#### Changes for CSV generator script

- [x] change date format for all date fields from ISO to YYYY-MM-DD
- [x] create multiple columns for all multi select fields
    - currently multi selects are stored in a single column as an array, ie: [term, term, term]
    - the change is to make a column for each value in the multi select, so each value in the array should have it’s own column, like purpose_1, purpose_2, purpose_3, purpose_4, purpose_5. (to a max of 5)
- [x] change all binary variables to use 0 and 1
    -  we have variables that report “TRUE” or “FALSE”, and others that report “yes” or “no”. homogenize these values as 0 and 1 across all fields like this.
- [x] include collections as a new column

#### Changes in DB/Webapp

- [x] check what max count is on all multi selects
    - are there any over 5? 
    - what should we do with options over 5? delete them?
- [x] limit all multi selects to max 5 if there is not limit on it yet
- [x] duplicate values
    - In scope_of_influence, we see that the original coding strategy generates duplicate values. In this case, we have information for “metropolitan_area” and “metropolitan” and we count them as separate categories. I suggest we make sure that the values matches so we are not missreporting some of these values.
    - we need to generate a list of all fields that contain duplicate values

**Comment by paninee** [comment]
Sample CSV

[participedia-data-cases.zip](https://github.com/participedia/api/files/5343548/participedia-data-cases.zip)

**Comment by paninee** [comment]
Cleaned up following duplicate values in DB ased on api/helpers/shared-field-options.js

**scope_of_influence**
citytown => city/town
metropolitan_area => metropolitan
neighborhood => neighbourhood

**Comment by ascott** [comment]
@jesicarson  @paninee here is a spreadsheet documenting the old db values that are still in our DB and need to be replaced with the equivalent new values. https://docs.google.com/spreadsheets/d/12my0Il-4vFRcFefqJzE4OPUZAMT7lB5FtTxJYuQLaVc/edit#gid=740848077.

i haven't populated the new values column yet. i think some are likely obvious but others may not be. i think we should fill in the new values we want to update the old values with in the spreadsheet before we update the DB to make sure we get the replacements all right.

**Comment by jesicarson** [comment]
I am almost certain that scott has a spreadsheet somewhere that maps all the old values to the new ones. @plscully can you help us find this?

**Comment by plscully** [comment]
@jesicarson I'm not sure which "old values" you are referring to, but perhaps the spreadsheets in this folder might be what you're looking for. They map the database keys to the reader view labels https://drive.google.com/drive/folders/1dQGOk8p1bksxwcAYweBY8aAfWYNxEcLw?usp=sharing 
.

**Comment by jesicarson** [comment]
@plscully you might be right i could have been thinking of that project. but i'm sure at some point when the data model was first updated we had to do an exercise in mapping values from the old model to the new one. is that ringing any bells? thanks!

@ascott if pat can't dig up that old mapping work, what is the best way for us to help you now?

**Comment by plscully** [comment]
This might be what you're looking for  https://docs.google.com/spreadsheets/d/178dCCFL-gOFj0bFP-H7iXYTRBS64W2pQ8hmQYmjBJn0/edit#gid=1137838561 
... My guess is that Scott wouldn't mind you asking him about this.

**Comment by paninee** [comment]
@ascott Is this CSV final? https://docs.google.com/spreadsheets/d/12my0Il-4vFRcFefqJzE4OPUZAMT7lB5FtTxJYuQLaVc/edit#gid=740848077

**Comment by ascott** [comment]
@ascott no it's not. we need to get the new value field populated. we are tracking down the document that mapped the old values to the new values. i'll post here when the csv is final.

**Comment by ascott** [comment]
thanks for that doc @plscully, it looks like it has the info we need for cases to fill in the [mapping document](https://docs.google.com/spreadsheets/d/12my0Il-4vFRcFefqJzE4OPUZAMT7lB5FtTxJYuQLaVc/edit#gid=740848077). do you also have equivalent docs for organizations and methods?

@jesicarson the next step is to review [Case Fixed Forms V3- Updated 27 May 2017](https://docs.google.com/spreadsheets/d/178dCCFL-gOFj0bFP-H7iXYTRBS64W2pQ8hmQYmjBJn0/edit#gid=1137838561) and fill in the new values based on the equivalent value in the new model. i can take a first pass at it and then we can review to make sure it's correct before we update the database.

**Comment by plscully** [comment]
@ascott I think I found them! Here is methods https://docs.google.com/spreadsheets/d/1z5lxbSVANhAL0QEfcz2jv6qctu7I0bdbNQrwulvVCG8/edit#gid=671339507

**Comment by plscully** [comment]
@ascott And here is organizations https://docs.google.com/spreadsheets/d/15D5WDW5Ma5KvxxYFSrrlG98cnUAaKIL2nOxE9--4s6Q/edit#gid=678179084

**Comment by plscully** [comment]
@ascott Sorry for not having these better organized, but based on how clean the docs are and their dates, the spreadsheets in this folder appear to be the most recent ones. https://drive.google.com/drive/folders/179gsG3teMgFTWaZgodPYOFYL7LUZCBNZ?usp=sharing

**Comment by plscully** [comment]
@jesicarson Once we figure out which files are which, let's schedule time to work together on re-organizing the files & folders so that it is easier to find things related to the data model updates.

**Comment by ascott** [comment]
@paninee jesi and i finished up the spreadsheet and the new values are now updated. lhttps://docs.google.com/spreadsheets/d/12my0Il-4vFRcFefqJzE4OPUZAMT7lB5FtTxJYuQLaVc/edit#gid=740848077
