### ISSUE TITLE
[DEV] Set up tracking for new events in analytics

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#989]
Homepage
- Clicks on stats
- Secondary search interaction
- Browse all entries
- Click the title of the hero slide
- Click news articles
- Interacting with the map

Search page
- Click filters button
- Click csv button

**Comment by jesicarson** [comment]
Tracking events spreadsheet https://docs.google.com/spreadsheets/d/1WlYD1JAiJteLp5CZ-E7so23Y9Bmv4EwaxCN5A0ARngA/edit

**Comment by ascott** [comment]
let's just complete the following for this issue:
![Screen Shot 2020-12-14 at 12 34 37 PM](https://user-images.githubusercontent.com/130878/102132663-c1fa5100-3e08-11eb-9d60-5220f60af556.png)

**Comment by paninee** [comment]
![image](https://user-images.githubusercontent.com/29439995/104470210-5376f300-556e-11eb-99b3-3ad7a537be52.png)
![image](https://user-images.githubusercontent.com/29439995/104470231-596cd400-556e-11eb-9285-41f9479e6dd8.png)

**Comment by paninee** [comment]
Deployed and tested on both stage and prod.
