### ISSUE TITLE
[DEV] Add new names to list of collaborators on about page

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#990]
David Talukder
Centre d'Etude de la Vie Politique (CEVIPOL)
Université libre de Bruxelles

* * * * * * * *

Julien Vrydagh
Department of Political Science
Vrije Universiteit Brussel and Université catholique de Louvain

**Comment by plscully** [comment]
@ascott Please let me know when this is done so that I can notify David and Julien.

**Comment by ascott** [comment]
@plscully these changes are live now

**Comment by plscully** [comment]
@ascott Thank you!
